[2025-03-10T00:16:14.852+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T00:16:14.902+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-10T00:16:12.642363+00:00 [queued]>
[2025-03-10T00:16:14.918+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-10T00:16:12.642363+00:00 [queued]>
[2025-03-10T00:16:14.919+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-10T00:16:14.961+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): submit_spark_gcs_job> on 2025-03-10 00:16:12.642363+00:00
[2025-03-10T00:16:14.981+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_gcs_job', 'submit_spark_gcs_job', 'manual__2025-03-10T00:16:12.642363+00:00', '--job-id', '467', '--raw', '--subdir', 'DAGS_FOLDER/gcs_conn_test.py', '--cfg-path', '/tmp/tmpy8mby24f']
[2025-03-10T00:16:15.007+0000] {standard_task_runner.py:105} INFO - Job 467: Subtask submit_spark_gcs_job
[2025-03-10T00:16:15.035+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=907) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-10T00:16:15.037+0000] {standard_task_runner.py:72} INFO - Started process 908 to run task
[2025-03-10T00:16:15.228+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-10T00:16:12.642363+00:00 [running]> on host 27f453beda85
[2025-03-10T00:16:15.457+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_gcs_job' AIRFLOW_CTX_TASK_ID='submit_spark_gcs_job' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:16:12.642363+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T00:16:12.642363+00:00'
[2025-03-10T00:16:15.459+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-10T00:16:15.537+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-03-10T00:16:15.541+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py
[2025-03-10T00:16:15.866+0000] {spark_submit.py:641} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-03-10T00:16:19.772+0000] {spark_submit.py:641} INFO - Using properties file: null
[2025-03-10T00:16:20.178+0000] {spark_submit.py:641} INFO - Parsed arguments:
[2025-03-10T00:16:20.178+0000] {spark_submit.py:641} INFO - master                  spark://spark:7077
[2025-03-10T00:16:20.179+0000] {spark_submit.py:641} INFO - remote                  null
[2025-03-10T00:16:20.180+0000] {spark_submit.py:641} INFO - deployMode              client
[2025-03-10T00:16:20.181+0000] {spark_submit.py:641} INFO - executorMemory          2g
[2025-03-10T00:16:20.181+0000] {spark_submit.py:641} INFO - executorCores           1
[2025-03-10T00:16:20.182+0000] {spark_submit.py:641} INFO - totalExecutorCores      null
[2025-03-10T00:16:20.183+0000] {spark_submit.py:641} INFO - propertiesFile          null
[2025-03-10T00:16:20.183+0000] {spark_submit.py:641} INFO - driverMemory            null
[2025-03-10T00:16:20.183+0000] {spark_submit.py:641} INFO - driverCores             null
[2025-03-10T00:16:20.184+0000] {spark_submit.py:641} INFO - driverExtraClassPath    null
[2025-03-10T00:16:20.184+0000] {spark_submit.py:641} INFO - driverExtraLibraryPath  null
[2025-03-10T00:16:20.184+0000] {spark_submit.py:641} INFO - driverExtraJavaOptions  null
[2025-03-10T00:16:20.185+0000] {spark_submit.py:641} INFO - supervise               false
[2025-03-10T00:16:20.185+0000] {spark_submit.py:641} INFO - queue                   null
[2025-03-10T00:16:20.186+0000] {spark_submit.py:641} INFO - numExecutors            2
[2025-03-10T00:16:20.186+0000] {spark_submit.py:641} INFO - files                   null
[2025-03-10T00:16:20.187+0000] {spark_submit.py:641} INFO - pyFiles                 null
[2025-03-10T00:16:20.189+0000] {spark_submit.py:641} INFO - archives                null
[2025-03-10T00:16:20.189+0000] {spark_submit.py:641} INFO - mainClass               null
[2025-03-10T00:16:20.190+0000] {spark_submit.py:641} INFO - primaryResource         file:/opt/***/jobs/gcc_test_job.py
[2025-03-10T00:16:20.190+0000] {spark_submit.py:641} INFO - name                    arrow-spark
[2025-03-10T00:16:20.190+0000] {spark_submit.py:641} INFO - childArgs               []
[2025-03-10T00:16:20.192+0000] {spark_submit.py:641} INFO - jars                    file:/opt/***/jars/gcs-connector-hadoop3-2.2.0.jar
[2025-03-10T00:16:20.192+0000] {spark_submit.py:641} INFO - packages                null
[2025-03-10T00:16:20.193+0000] {spark_submit.py:641} INFO - packagesExclusions      null
[2025-03-10T00:16:20.194+0000] {spark_submit.py:641} INFO - repositories            null
[2025-03-10T00:16:20.194+0000] {spark_submit.py:641} INFO - verbose                 true
[2025-03-10T00:16:20.194+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:16:20.197+0000] {spark_submit.py:641} INFO - Spark properties used, including those specified through
[2025-03-10T00:16:20.198+0000] {spark_submit.py:641} INFO - --conf and those from the properties file null:
[2025-03-10T00:16:20.199+0000] {spark_submit.py:641} INFO - (spark.executor.cores,1)
[2025-03-10T00:16:20.202+0000] {spark_submit.py:641} INFO - (spark.executor.instances,2)
[2025-03-10T00:16:20.203+0000] {spark_submit.py:641} INFO - (spark.executor.memory,2g)
[2025-03-10T00:16:20.206+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.enable,true)
[2025-03-10T00:16:20.206+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.json.keyfile,/opt/***/keys/first-key.json)
[2025-03-10T00:16:20.207+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.impl,com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem)
[2025-03-10T00:16:20.207+0000] {spark_submit.py:641} INFO - (spark.master,spark://spark:7077)
[2025-03-10T00:16:20.207+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:16:20.207+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:16:20.808+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:20 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-10T00:16:21.369+0000] {spark_submit.py:641} INFO - Main class:
[2025-03-10T00:16:21.369+0000] {spark_submit.py:641} INFO - org.apache.spark.deploy.PythonRunner
[2025-03-10T00:16:21.370+0000] {spark_submit.py:641} INFO - Arguments:
[2025-03-10T00:16:21.371+0000] {spark_submit.py:641} INFO - file:/opt/***/jobs/gcc_test_job.py
[2025-03-10T00:16:21.371+0000] {spark_submit.py:641} INFO - null
[2025-03-10T00:16:21.377+0000] {spark_submit.py:641} INFO - Spark config:
[2025-03-10T00:16:21.377+0000] {spark_submit.py:641} INFO - (spark.app.name,arrow-spark)
[2025-03-10T00:16:21.378+0000] {spark_submit.py:641} INFO - (spark.app.submitTime,1741565781325)
[2025-03-10T00:16:21.380+0000] {spark_submit.py:641} INFO - (spark.executor.cores,1)
[2025-03-10T00:16:21.382+0000] {spark_submit.py:641} INFO - (spark.executor.instances,2)
[2025-03-10T00:16:21.383+0000] {spark_submit.py:641} INFO - (spark.executor.memory,2g)
[2025-03-10T00:16:21.383+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.enable,true)
[2025-03-10T00:16:21.384+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.json.keyfile,/opt/***/keys/first-key.json)
[2025-03-10T00:16:21.384+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.impl,com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem)
[2025-03-10T00:16:21.384+0000] {spark_submit.py:641} INFO - (spark.jars,file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar)
[2025-03-10T00:16:21.385+0000] {spark_submit.py:641} INFO - (spark.master,spark://spark:7077)
[2025-03-10T00:16:21.385+0000] {spark_submit.py:641} INFO - (spark.repl.local.jars,file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar)
[2025-03-10T00:16:21.389+0000] {spark_submit.py:641} INFO - (spark.submit.deployMode,client)
[2025-03-10T00:16:21.390+0000] {spark_submit.py:641} INFO - (spark.submit.pyFiles,)
[2025-03-10T00:16:21.390+0000] {spark_submit.py:641} INFO - Classpath elements:
[2025-03-10T00:16:21.391+0000] {spark_submit.py:641} INFO - file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar
[2025-03-10T00:16:21.392+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:16:21.392+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:16:23.940+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:23 INFO SparkContext: Running Spark version 3.5.5
[2025-03-10T00:16:23.942+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:23 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-03-10T00:16:23.943+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:23 INFO SparkContext: Java version 17.0.14
[2025-03-10T00:16:23.988+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:23 INFO ResourceUtils: ==============================================================
[2025-03-10T00:16:23.989+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:23 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-10T00:16:23.991+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:23 INFO ResourceUtils: ==============================================================
[2025-03-10T00:16:23.992+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:23 INFO SparkContext: Submitted application: GCSConnectorTest
[2025-03-10T00:16:24.034+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:24 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 2048, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-10T00:16:24.048+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:24 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2025-03-10T00:16:24.051+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:24 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-10T00:16:24.206+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:24 INFO SecurityManager: Changing view acls to: ***
[2025-03-10T00:16:24.207+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:24 INFO SecurityManager: Changing modify acls to: ***
[2025-03-10T00:16:24.208+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:24 INFO SecurityManager: Changing view acls groups to:
[2025-03-10T00:16:24.209+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:24 INFO SecurityManager: Changing modify acls groups to:
[2025-03-10T00:16:24.210+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:24 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-03-10T00:16:24.811+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:24 INFO Utils: Successfully started service 'sparkDriver' on port 40825.
[2025-03-10T00:16:24.899+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:24 INFO SparkEnv: Registering MapOutputTracker
[2025-03-10T00:16:24.974+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:24 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-10T00:16:25.053+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:25 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-10T00:16:25.054+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:25 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-10T00:16:25.061+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:25 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-10T00:16:25.157+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:25 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-366663df-b89e-4c36-8025-3d3f281b5c92
[2025-03-10T00:16:25.240+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:25 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-10T00:16:25.346+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:25 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-10T00:16:25.800+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:25 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-10T00:16:26.011+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:26 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-10T00:16:26.081+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:26 INFO SparkContext: Added JAR file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar at spark://27f453beda85:40825/jars/gcs-connector-hadoop3-2.2.0.jar with timestamp 1741565783925
[2025-03-10T00:16:26.606+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:26 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2025-03-10T00:16:26.795+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:26 INFO TransportClientFactory: Successfully created connection to spark/172.19.0.5:7077 after 61 ms (0 ms spent in bootstraps)
[2025-03-10T00:16:27.734+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:27 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250310001627-0000
[2025-03-10T00:16:27.765+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:27 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37247.
[2025-03-10T00:16:27.766+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:27 INFO NettyBlockTransferService: Server created on 27f453beda85:37247
[2025-03-10T00:16:27.769+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:27 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-10T00:16:27.783+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:27 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 27f453beda85, 37247, None)
[2025-03-10T00:16:27.801+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:27 INFO BlockManagerMasterEndpoint: Registering block manager 27f453beda85:37247 with 434.4 MiB RAM, BlockManagerId(driver, 27f453beda85, 37247, None)
[2025-03-10T00:16:27.813+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:27 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 27f453beda85, 37247, None)
[2025-03-10T00:16:27.820+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:27 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 27f453beda85, 37247, None)
[2025-03-10T00:16:27.865+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:27 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250310001627-0000/0 on worker-20250310001523-172.19.0.6-39949 (172.19.0.6:39949) with 1 core(s)
[2025-03-10T00:16:27.874+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:27 INFO StandaloneSchedulerBackend: Granted executor ID app-20250310001627-0000/0 on hostPort 172.19.0.6:39949 with 1 core(s), 2.0 GiB RAM
[2025-03-10T00:16:28.474+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:28 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-10T00:16:29.013+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:29 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250310001627-0000/0 is now RUNNING
[2025-03-10T00:16:29.078+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:29 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-10T00:16:29.086+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:29 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2025-03-10T00:16:36.859+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:36 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.19.0.6:59114) with ID 0,  ResourceProfileId 0
[2025-03-10T00:16:36.984+0000] {spark_submit.py:641} INFO - 25/03/10 00:16:36 INFO BlockManagerMasterEndpoint: Registering block manager 172.19.0.6:33105 with 1048.8 MiB RAM, BlockManagerId(0, 172.19.0.6, 33105, None)
[2025-03-10T00:19:30.153+0000] {spark_submit.py:641} INFO - 25/03/10 00:19:30 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: gs://final_ecom_taxi-data-447320/products.csv.
[2025-03-10T00:19:30.155+0000] {spark_submit.py:641} INFO - java.io.IOException: Error accessing gs://final_ecom_taxi-data-447320/products.csv
[2025-03-10T00:19:30.156+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getObject(GoogleCloudStorageImpl.java:1950)
[2025-03-10T00:19:30.157+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfo(GoogleCloudStorageImpl.java:1838)
[2025-03-10T00:19:30.158+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.getFileInfoInternal(GoogleCloudStorageFileSystem.java:1065)
[2025-03-10T00:19:30.158+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystem.getFileInfo(GoogleCloudStorageFileSystem.java:1039)
[2025-03-10T00:19:30.159+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getFileStatus(GoogleHadoopFileSystemBase.java:948)
[2025-03-10T00:19:30.160+0000] {spark_submit.py:641} INFO - at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1777)
[2025-03-10T00:19:30.160+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
[2025-03-10T00:19:30.161+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
[2025-03-10T00:19:30.162+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-03-10T00:19:30.162+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-03-10T00:19:30.163+0000] {spark_submit.py:641} INFO - at scala.Option.getOrElse(Option.scala:189)
[2025-03-10T00:19:30.163+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-03-10T00:19:30.164+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:538)
[2025-03-10T00:19:30.164+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-10T00:19:30.165+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-03-10T00:19:30.165+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-10T00:19:30.165+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-03-10T00:19:30.166+0000] {spark_submit.py:641} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-10T00:19:30.166+0000] {spark_submit.py:641} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-10T00:19:30.166+0000] {spark_submit.py:641} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-10T00:19:30.167+0000] {spark_submit.py:641} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-10T00:19:30.167+0000] {spark_submit.py:641} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-10T00:19:30.167+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-10T00:19:30.168+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-10T00:19:30.168+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-10T00:19:30.169+0000] {spark_submit.py:641} INFO - Caused by: java.net.UnknownHostException: oauth2.googleapis.com
[2025-03-10T00:19:30.169+0000] {spark_submit.py:641} INFO - at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:572)
[2025-03-10T00:19:30.169+0000] {spark_submit.py:641} INFO - at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[2025-03-10T00:19:30.169+0000] {spark_submit.py:641} INFO - at java.base/java.net.Socket.connect(Socket.java:633)
[2025-03-10T00:19:30.170+0000] {spark_submit.py:641} INFO - at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[2025-03-10T00:19:30.170+0000] {spark_submit.py:641} INFO - at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[2025-03-10T00:19:30.170+0000] {spark_submit.py:641} INFO - at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
[2025-03-10T00:19:30.171+0000] {spark_submit.py:641} INFO - at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
[2025-03-10T00:19:30.171+0000] {spark_submit.py:641} INFO - at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[2025-03-10T00:19:30.171+0000] {spark_submit.py:641} INFO - at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[2025-03-10T00:19:30.171+0000] {spark_submit.py:641} INFO - at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[2025-03-10T00:19:30.172+0000] {spark_submit.py:641} INFO - at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1257)
[2025-03-10T00:19:30.172+0000] {spark_submit.py:641} INFO - at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1143)
[2025-03-10T00:19:30.172+0000] {spark_submit.py:641} INFO - at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[2025-03-10T00:19:30.173+0000] {spark_submit.py:641} INFO - at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1466)
[2025-03-10T00:19:30.173+0000] {spark_submit.py:641} INFO - at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1437)
[2025-03-10T00:19:30.173+0000] {spark_submit.py:641} INFO - at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)
[2025-03-10T00:19:30.173+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113)
[2025-03-10T00:19:30.173+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
[2025-03-10T00:19:30.174+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
[2025-03-10T00:19:30.174+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:322)
[2025-03-10T00:19:30.174+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:346)
[2025-03-10T00:19:30.174+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialFactory$GoogleCredentialWithRetry.executeRefreshToken(CredentialFactory.java:170)
[2025-03-10T00:19:30.174+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:494)
[2025-03-10T00:19:30.174+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
[2025-03-10T00:19:30.174+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:880)
[2025-03-10T00:19:30.175+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
[2025-03-10T00:19:30.175+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
[2025-03-10T00:19:30.175+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
[2025-03-10T00:19:30.175+0000] {spark_submit.py:641} INFO - at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getObject(GoogleCloudStorageImpl.java:1944)
[2025-03-10T00:19:30.175+0000] {spark_submit.py:641} INFO - ... 24 more
[2025-03-10T00:20:59.958+0000] {spark_submit.py:641} INFO - 25/03/10 00:20:59 INFO InMemoryFileIndex: It took 364 ms to list leaf files for 1 paths.
[2025-03-10T00:21:01.095+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:01 INFO InMemoryFileIndex: It took 78 ms to list leaf files for 1 paths.
[2025-03-10T00:21:07.262+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:07 INFO FileSourceStrategy: Pushed Filters:
[2025-03-10T00:21:07.290+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:07 INFO FileSourceStrategy: Post-Scan Filters: (length(trim(value#0, None)) > 0)
[2025-03-10T00:21:08.643+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:08 INFO CodeGenerator: Code generated in 415.317481 ms
[2025-03-10T00:21:08.732+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:08 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 201.4 KiB, free 434.2 MiB)
[2025-03-10T00:21:08.960+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:08 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 34.9 KiB, free 434.2 MiB)
[2025-03-10T00:21:08.965+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:08 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 27f453beda85:37247 (size: 34.9 KiB, free: 434.4 MiB)
[2025-03-10T00:21:08.975+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:08 INFO SparkContext: Created broadcast 0 from csv at NativeMethodAccessorImpl.java:0
[2025-03-10T00:21:08.993+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:08 INFO FileSourceScanExec: Planning scan with bin packing, max size: 4838318 bytes, open cost is considered as scanning 4194304 bytes.
[2025-03-10T00:21:09.309+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO SparkContext: Starting job: csv at NativeMethodAccessorImpl.java:0
[2025-03-10T00:21:09.478+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO DAGScheduler: Got job 0 (csv at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2025-03-10T00:21:09.479+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO DAGScheduler: Final stage: ResultStage 0 (csv at NativeMethodAccessorImpl.java:0)
[2025-03-10T00:21:09.481+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO DAGScheduler: Parents of final stage: List()
[2025-03-10T00:21:09.483+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO DAGScheduler: Missing parents: List()
[2025-03-10T00:21:09.500+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[3] at csv at NativeMethodAccessorImpl.java:0), which has no missing parents
[2025-03-10T00:21:09.699+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 13.5 KiB, free 434.2 MiB)
[2025-03-10T00:21:09.731+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 6.4 KiB, free 434.1 MiB)
[2025-03-10T00:21:09.732+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 27f453beda85:37247 (size: 6.4 KiB, free: 434.4 MiB)
[2025-03-10T00:21:09.734+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1585
[2025-03-10T00:21:09.768+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[3] at csv at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2025-03-10T00:21:09.773+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2025-03-10T00:21:09.816+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:09 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:21:10.603+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:10 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 172.19.0.6:33105 (size: 6.4 KiB, free: 1048.8 MiB)
[2025-03-10T00:21:13.900+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:13 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.19.0.6:33105 (size: 34.9 KiB, free: 1048.8 MiB)
[2025-03-10T00:21:15.228+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:21:15.229+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:21:15.230+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:21:15.230+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:21:15.230+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:21:15.231+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:21:15.231+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:21:15.231+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:21:15.232+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:21:15.232+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:21:15.232+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:21:15.233+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:21:15.233+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:21:15.234+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:21:15.235+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:21:15.235+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:21:15.242+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:21:15.242+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:21:15.242+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:21:15.243+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:21:15.243+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:21:15.243+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:21:15.243+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:21:15.243+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:21:15.243+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:21:15.243+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:21:15.243+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:21:15.244+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:21:15.244+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 1) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:21:15.376+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on 172.19.0.6, executor 0: org.apache.spark.SparkFileNotFoundException (/opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:21:15.376+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.) [duplicate 1]
[2025-03-10T00:21:15.377+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 2) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:21:15.459+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 INFO TaskSetManager: Lost task 0.2 in stage 0.0 (TID 2) on 172.19.0.6, executor 0: org.apache.spark.SparkFileNotFoundException (/opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:21:15.460+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.) [duplicate 2]
[2025-03-10T00:21:15.462+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 3) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:21:15.501+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 3) on 172.19.0.6, executor 0: org.apache.spark.SparkFileNotFoundException (/opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:21:15.507+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.) [duplicate 3]
[2025-03-10T00:21:15.509+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
[2025-03-10T00:21:15.511+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2025-03-10T00:21:15.513+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 INFO TaskSchedulerImpl: Cancelling stage 0
[2025-03-10T00:21:15.516+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage cancelled: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:21:15.518+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:21:15.519+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:21:15.520+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:21:15.520+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:21:15.526+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:21:15.526+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:21:15.526+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:21:15.527+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:21:15.527+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:21:15.527+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:21:15.527+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:21:15.528+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:21:15.528+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:21:15.528+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:21:15.529+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:21:15.531+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:21:15.534+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:21:15.535+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:21:15.535+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:21:15.535+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:21:15.536+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:21:15.536+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:21:15.536+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:21:15.541+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:21:15.542+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:21:15.542+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:21:15.542+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:21:15.543+0000] {spark_submit.py:641} INFO - Driver stacktrace:
[2025-03-10T00:21:15.543+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 INFO DAGScheduler: ResultStage 0 (csv at NativeMethodAccessorImpl.java:0) failed in 5.973 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:21:15.544+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:21:15.551+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:21:15.552+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:21:15.552+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:21:15.552+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:21:15.553+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:21:15.553+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:21:15.555+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:21:15.555+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:21:15.556+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:21:15.556+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:21:15.556+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:21:15.556+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:21:15.557+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:21:15.557+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:21:15.558+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:21:15.558+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:21:15.559+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:21:15.559+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:21:15.559+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:21:15.560+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:21:15.560+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:21:15.560+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:21:15.561+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:21:15.561+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:21:15.562+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:21:15.562+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:21:15.563+0000] {spark_submit.py:641} INFO - Driver stacktrace:
[2025-03-10T00:21:15.563+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:15 INFO DAGScheduler: Job 0 failed: csv at NativeMethodAccessorImpl.java:0, took 6.229555 s
[2025-03-10T00:21:15.848+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-03-10T00:21:15.848+0000] {spark_submit.py:641} INFO - File "/opt/***/jobs/gcc_test_job.py", line 11, in <module>
[2025-03-10T00:21:15.850+0000] {spark_submit.py:641} INFO - df = spark.read.csv(gcs_bucket_path, header=True)
[2025-03-10T00:21:15.850+0000] {spark_submit.py:641} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-10T00:21:15.851+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-03-10T00:21:15.853+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-10T00:21:15.853+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-03-10T00:21:15.854+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-03-10T00:21:15.902+0000] {spark_submit.py:641} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o33.csv.
[2025-03-10T00:21:15.903+0000] {spark_submit.py:641} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:21:15.905+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:21:15.906+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:21:15.907+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:21:15.908+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:21:15.909+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:21:15.910+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:21:15.910+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:21:15.911+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:21:15.911+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:21:15.912+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:21:15.913+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:21:15.914+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:21:15.914+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:21:15.915+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:21:15.915+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:21:15.916+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:21:15.917+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:21:15.918+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:21:15.918+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:21:15.918+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:21:15.919+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:21:15.919+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:21:15.920+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:21:15.921+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:21:15.921+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:21:15.921+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:21:15.922+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:21:15.922+0000] {spark_submit.py:641} INFO - Driver stacktrace:
[2025-03-10T00:21:15.923+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2025-03-10T00:21:15.923+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2025-03-10T00:21:15.924+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2025-03-10T00:21:15.924+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-03-10T00:21:15.925+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-03-10T00:21:15.925+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-03-10T00:21:15.926+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2025-03-10T00:21:15.927+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2025-03-10T00:21:15.928+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2025-03-10T00:21:15.928+0000] {spark_submit.py:641} INFO - at scala.Option.foreach(Option.scala:407)
[2025-03-10T00:21:15.929+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2025-03-10T00:21:15.929+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2025-03-10T00:21:15.929+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2025-03-10T00:21:15.930+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2025-03-10T00:21:15.930+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-03-10T00:21:15.930+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2025-03-10T00:21:15.931+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2025-03-10T00:21:15.931+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2025-03-10T00:21:15.932+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2025-03-10T00:21:15.932+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:530)
[2025-03-10T00:21:15.933+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:483)
[2025-03-10T00:21:15.934+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:61)
[2025-03-10T00:21:15.935+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:4333)
[2025-03-10T00:21:15.936+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:3316)
[2025-03-10T00:21:15.937+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:4323)
[2025-03-10T00:21:15.937+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
[2025-03-10T00:21:15.938+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:4321)
[2025-03-10T00:21:15.938+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-03-10T00:21:15.938+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-03-10T00:21:15.939+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-03-10T00:21:15.939+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-03-10T00:21:15.939+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-03-10T00:21:15.940+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4321)
[2025-03-10T00:21:15.940+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.head(Dataset.scala:3316)
[2025-03-10T00:21:15.940+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.take(Dataset.scala:3539)
[2025-03-10T00:21:15.941+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.csv.TextInputCSVDataSource$.infer(CSVDataSource.scala:111)
[2025-03-10T00:21:15.941+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.csv.CSVDataSource.inferSchema(CSVDataSource.scala:64)
[2025-03-10T00:21:15.941+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat.inferSchema(CSVFileFormat.scala:62)
[2025-03-10T00:21:15.942+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:208)
[2025-03-10T00:21:15.942+0000] {spark_submit.py:641} INFO - at scala.Option.orElse(Option.scala:447)
[2025-03-10T00:21:15.942+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:205)
[2025-03-10T00:21:15.943+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:407)
[2025-03-10T00:21:15.943+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-03-10T00:21:15.943+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-03-10T00:21:15.943+0000] {spark_submit.py:641} INFO - at scala.Option.getOrElse(Option.scala:189)
[2025-03-10T00:21:15.943+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-03-10T00:21:15.944+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:538)
[2025-03-10T00:21:15.944+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-10T00:21:15.944+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-03-10T00:21:15.944+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-10T00:21:15.945+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-03-10T00:21:15.945+0000] {spark_submit.py:641} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-10T00:21:15.945+0000] {spark_submit.py:641} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-10T00:21:15.945+0000] {spark_submit.py:641} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-10T00:21:15.946+0000] {spark_submit.py:641} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-10T00:21:15.946+0000] {spark_submit.py:641} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-10T00:21:15.946+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-10T00:21:15.946+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-10T00:21:15.947+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-10T00:21:15.949+0000] {spark_submit.py:641} INFO - Caused by: org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:21:15.950+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:21:15.950+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:21:15.951+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:21:15.951+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:21:15.952+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:21:15.952+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:21:15.952+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:21:15.952+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:21:15.953+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:21:15.953+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:21:15.953+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:21:15.954+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:21:15.955+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:21:15.955+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:21:15.955+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:21:15.955+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:21:15.956+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:21:15.956+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:21:15.956+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:21:15.956+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:21:15.957+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:21:15.957+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:21:15.957+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:21:15.957+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:21:15.958+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:21:15.958+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:21:15.958+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:21:16.101+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-10T00:21:16.102+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-10T00:21:16.121+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO SparkUI: Stopped Spark web UI at http://27f453beda85:4040
[2025-03-10T00:21:16.127+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-03-10T00:21:16.128+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-03-10T00:21:16.174+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-10T00:21:16.234+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO MemoryStore: MemoryStore cleared
[2025-03-10T00:21:16.239+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO BlockManager: BlockManager stopped
[2025-03-10T00:21:16.259+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-10T00:21:16.275+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-10T00:21:16.358+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO SparkContext: Successfully stopped SparkContext
[2025-03-10T00:21:16.358+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO ShutdownHookManager: Shutdown hook called
[2025-03-10T00:21:16.359+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO ShutdownHookManager: Deleting directory /tmp/spark-da4a0072-dd71-4c7a-8798-b336f738899a
[2025-03-10T00:21:16.397+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO ShutdownHookManager: Deleting directory /tmp/spark-4be4e2bc-a740-47c1-84f2-a5c61afd2ce2/pyspark-20d94382-bfbd-4a57-8459-c085ba6e3e79
[2025-03-10T00:21:16.413+0000] {spark_submit.py:641} INFO - 25/03/10 00:21:16 INFO ShutdownHookManager: Deleting directory /tmp/spark-4be4e2bc-a740-47c1-84f2-a5c61afd2ce2
[2025-03-10T00:21:16.652+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py. Error code is: 1.
[2025-03-10T00:21:16.756+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_gcs_job, task_id=submit_spark_gcs_job, run_id=manual__2025-03-10T00:16:12.642363+00:00, execution_date=20250310T001612, start_date=20250310T001614, end_date=20250310T002116
[2025-03-10T00:21:16.889+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-10T00:21:16.894+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 467 for task submit_spark_gcs_job (Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py. Error code is: 1.; 908)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py. Error code is: 1.
[2025-03-10T00:21:16.949+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T00:21:16.997+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T00:21:17.000+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
