[2025-03-10T00:36:25.510+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T00:36:25.541+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-10T00:31:02.222494+00:00 [queued]>
[2025-03-10T00:36:25.551+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-10T00:31:02.222494+00:00 [queued]>
[2025-03-10T00:36:25.552+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-03-10T00:36:25.565+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): submit_spark_gcs_job> on 2025-03-10 00:31:02.222494+00:00
[2025-03-10T00:36:25.577+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1694) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-10T00:36:25.575+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_gcs_job', 'submit_spark_gcs_job', 'manual__2025-03-10T00:31:02.222494+00:00', '--job-id', '470', '--raw', '--subdir', 'DAGS_FOLDER/gcs_conn_test.py', '--cfg-path', '/tmp/tmp5y5oefzc']
[2025-03-10T00:36:25.578+0000] {standard_task_runner.py:72} INFO - Started process 1695 to run task
[2025-03-10T00:36:25.579+0000] {standard_task_runner.py:105} INFO - Job 470: Subtask submit_spark_gcs_job
[2025-03-10T00:36:25.629+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-10T00:31:02.222494+00:00 [running]> on host 27f453beda85
[2025-03-10T00:36:25.708+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_gcs_job' AIRFLOW_CTX_TASK_ID='submit_spark_gcs_job' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:31:02.222494+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T00:31:02.222494+00:00'
[2025-03-10T00:36:25.709+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-10T00:36:25.738+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-03-10T00:36:25.740+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py
[2025-03-10T00:36:25.785+0000] {spark_submit.py:641} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-03-10T00:36:27.804+0000] {spark_submit.py:641} INFO - Using properties file: null
[2025-03-10T00:36:27.955+0000] {spark_submit.py:641} INFO - Parsed arguments:
[2025-03-10T00:36:27.956+0000] {spark_submit.py:641} INFO - master                  spark://spark:7077
[2025-03-10T00:36:27.956+0000] {spark_submit.py:641} INFO - remote                  null
[2025-03-10T00:36:27.956+0000] {spark_submit.py:641} INFO - deployMode              client
[2025-03-10T00:36:27.957+0000] {spark_submit.py:641} INFO - executorMemory          2g
[2025-03-10T00:36:27.957+0000] {spark_submit.py:641} INFO - executorCores           1
[2025-03-10T00:36:27.957+0000] {spark_submit.py:641} INFO - totalExecutorCores      null
[2025-03-10T00:36:27.958+0000] {spark_submit.py:641} INFO - propertiesFile          null
[2025-03-10T00:36:27.958+0000] {spark_submit.py:641} INFO - driverMemory            null
[2025-03-10T00:36:27.958+0000] {spark_submit.py:641} INFO - driverCores             null
[2025-03-10T00:36:27.959+0000] {spark_submit.py:641} INFO - driverExtraClassPath    null
[2025-03-10T00:36:27.959+0000] {spark_submit.py:641} INFO - driverExtraLibraryPath  null
[2025-03-10T00:36:27.959+0000] {spark_submit.py:641} INFO - driverExtraJavaOptions  null
[2025-03-10T00:36:27.959+0000] {spark_submit.py:641} INFO - supervise               false
[2025-03-10T00:36:27.960+0000] {spark_submit.py:641} INFO - queue                   null
[2025-03-10T00:36:27.960+0000] {spark_submit.py:641} INFO - numExecutors            2
[2025-03-10T00:36:27.960+0000] {spark_submit.py:641} INFO - files                   null
[2025-03-10T00:36:27.961+0000] {spark_submit.py:641} INFO - pyFiles                 null
[2025-03-10T00:36:27.961+0000] {spark_submit.py:641} INFO - archives                null
[2025-03-10T00:36:27.962+0000] {spark_submit.py:641} INFO - mainClass               null
[2025-03-10T00:36:27.962+0000] {spark_submit.py:641} INFO - primaryResource         file:/opt/***/jobs/gcc_test_job.py
[2025-03-10T00:36:27.962+0000] {spark_submit.py:641} INFO - name                    arrow-spark
[2025-03-10T00:36:27.963+0000] {spark_submit.py:641} INFO - childArgs               []
[2025-03-10T00:36:27.963+0000] {spark_submit.py:641} INFO - jars                    file:/opt/***/jars/gcs-connector-hadoop3-2.2.0.jar
[2025-03-10T00:36:27.963+0000] {spark_submit.py:641} INFO - packages                null
[2025-03-10T00:36:27.963+0000] {spark_submit.py:641} INFO - packagesExclusions      null
[2025-03-10T00:36:27.964+0000] {spark_submit.py:641} INFO - repositories            null
[2025-03-10T00:36:27.964+0000] {spark_submit.py:641} INFO - verbose                 true
[2025-03-10T00:36:27.964+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:36:27.965+0000] {spark_submit.py:641} INFO - Spark properties used, including those specified through
[2025-03-10T00:36:27.965+0000] {spark_submit.py:641} INFO - --conf and those from the properties file null:
[2025-03-10T00:36:27.965+0000] {spark_submit.py:641} INFO - (spark.executor.cores,1)
[2025-03-10T00:36:27.975+0000] {spark_submit.py:641} INFO - (spark.executor.instances,2)
[2025-03-10T00:36:27.976+0000] {spark_submit.py:641} INFO - (spark.executor.memory,2g)
[2025-03-10T00:36:27.976+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.enable,true)
[2025-03-10T00:36:27.977+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.json.keyfile,/opt/***/keys/first-key.json)
[2025-03-10T00:36:27.977+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.impl,com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem)
[2025-03-10T00:36:27.978+0000] {spark_submit.py:641} INFO - (spark.master,spark://spark:7077)
[2025-03-10T00:36:27.978+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:36:27.979+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:36:28.335+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:28 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-10T00:36:28.639+0000] {spark_submit.py:641} INFO - Main class:
[2025-03-10T00:36:28.640+0000] {spark_submit.py:641} INFO - org.apache.spark.deploy.PythonRunner
[2025-03-10T00:36:28.641+0000] {spark_submit.py:641} INFO - Arguments:
[2025-03-10T00:36:28.641+0000] {spark_submit.py:641} INFO - file:/opt/***/jobs/gcc_test_job.py
[2025-03-10T00:36:28.641+0000] {spark_submit.py:641} INFO - null
[2025-03-10T00:36:28.643+0000] {spark_submit.py:641} INFO - Spark config:
[2025-03-10T00:36:28.644+0000] {spark_submit.py:641} INFO - (spark.app.name,arrow-spark)
[2025-03-10T00:36:28.644+0000] {spark_submit.py:641} INFO - (spark.app.submitTime,1741566988598)
[2025-03-10T00:36:28.645+0000] {spark_submit.py:641} INFO - (spark.executor.cores,1)
[2025-03-10T00:36:28.645+0000] {spark_submit.py:641} INFO - (spark.executor.instances,2)
[2025-03-10T00:36:28.645+0000] {spark_submit.py:641} INFO - (spark.executor.memory,2g)
[2025-03-10T00:36:28.645+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.enable,true)
[2025-03-10T00:36:28.646+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.json.keyfile,/opt/***/keys/first-key.json)
[2025-03-10T00:36:28.646+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.impl,com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem)
[2025-03-10T00:36:28.646+0000] {spark_submit.py:641} INFO - (spark.jars,file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar)
[2025-03-10T00:36:28.647+0000] {spark_submit.py:641} INFO - (spark.master,spark://spark:7077)
[2025-03-10T00:36:28.647+0000] {spark_submit.py:641} INFO - (spark.repl.local.jars,file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar)
[2025-03-10T00:36:28.647+0000] {spark_submit.py:641} INFO - (spark.submit.deployMode,client)
[2025-03-10T00:36:28.648+0000] {spark_submit.py:641} INFO - (spark.submit.pyFiles,)
[2025-03-10T00:36:28.648+0000] {spark_submit.py:641} INFO - Classpath elements:
[2025-03-10T00:36:28.648+0000] {spark_submit.py:641} INFO - file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar
[2025-03-10T00:36:28.649+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:36:28.649+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:36:29.991+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:29 INFO SparkContext: Running Spark version 3.5.5
[2025-03-10T00:36:29.991+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:29 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-03-10T00:36:29.992+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:29 INFO SparkContext: Java version 17.0.14
[2025-03-10T00:36:30.042+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO ResourceUtils: ==============================================================
[2025-03-10T00:36:30.044+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-10T00:36:30.045+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO ResourceUtils: ==============================================================
[2025-03-10T00:36:30.048+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO SparkContext: Submitted application: GCSConnectorTest
[2025-03-10T00:36:30.080+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 2048, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-10T00:36:30.099+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2025-03-10T00:36:30.104+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-10T00:36:30.188+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO SecurityManager: Changing view acls to: ***
[2025-03-10T00:36:30.192+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO SecurityManager: Changing modify acls to: ***
[2025-03-10T00:36:30.193+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO SecurityManager: Changing view acls groups to:
[2025-03-10T00:36:30.197+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO SecurityManager: Changing modify acls groups to:
[2025-03-10T00:36:30.198+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-03-10T00:36:30.479+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO Utils: Successfully started service 'sparkDriver' on port 40795.
[2025-03-10T00:36:30.505+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO SparkEnv: Registering MapOutputTracker
[2025-03-10T00:36:30.546+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-10T00:36:30.563+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-10T00:36:30.563+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-10T00:36:30.567+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-10T00:36:30.587+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-03797ea4-462a-4899-91c4-98f05e6b2e0d
[2025-03-10T00:36:30.602+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-10T00:36:30.637+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-10T00:36:30.837+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-10T00:36:30.949+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:30 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-10T00:36:31.012+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO SparkContext: Added JAR file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar at spark://27f453beda85:40795/jars/gcs-connector-hadoop3-2.2.0.jar with timestamp 1741566989972
[2025-03-10T00:36:31.172+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2025-03-10T00:36:31.244+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO TransportClientFactory: Successfully created connection to spark/172.19.0.5:7077 after 30 ms (0 ms spent in bootstraps)
[2025-03-10T00:36:31.379+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250310003631-0003
[2025-03-10T00:36:31.384+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250310003631-0003/0 on worker-20250310001523-172.19.0.6-39949 (172.19.0.6:39949) with 1 core(s)
[2025-03-10T00:36:31.386+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO StandaloneSchedulerBackend: Granted executor ID app-20250310003631-0003/0 on hostPort 172.19.0.6:39949 with 1 core(s), 2.0 GiB RAM
[2025-03-10T00:36:31.398+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46799.
[2025-03-10T00:36:31.399+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO NettyBlockTransferService: Server created on 27f453beda85:46799
[2025-03-10T00:36:31.401+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-10T00:36:31.414+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 27f453beda85, 46799, None)
[2025-03-10T00:36:31.416+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO BlockManagerMasterEndpoint: Registering block manager 27f453beda85:46799 with 434.4 MiB RAM, BlockManagerId(driver, 27f453beda85, 46799, None)
[2025-03-10T00:36:31.420+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 27f453beda85, 46799, None)
[2025-03-10T00:36:31.423+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 27f453beda85, 46799, None)
[2025-03-10T00:36:31.568+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250310003631-0003/0 is now RUNNING
[2025-03-10T00:36:31.909+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:31 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-10T00:36:32.307+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:32 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-10T00:36:32.320+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:32 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2025-03-10T00:36:36.543+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:36 INFO InMemoryFileIndex: It took 199 ms to list leaf files for 1 paths.
[2025-03-10T00:36:36.835+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:36 INFO InMemoryFileIndex: It took 82 ms to list leaf files for 1 paths.
[2025-03-10T00:36:37.413+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:37 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.19.0.6:33484) with ID 0,  ResourceProfileId 0
[2025-03-10T00:36:37.576+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:37 INFO BlockManagerMasterEndpoint: Registering block manager 172.19.0.6:36891 with 1048.8 MiB RAM, BlockManagerId(0, 172.19.0.6, 36891, None)
[2025-03-10T00:36:39.589+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:39 INFO FileSourceStrategy: Pushed Filters:
[2025-03-10T00:36:39.593+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:39 INFO FileSourceStrategy: Post-Scan Filters: (length(trim(value#0, None)) > 0)
[2025-03-10T00:36:40.141+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO CodeGenerator: Code generated in 159.890122 ms
[2025-03-10T00:36:40.221+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 201.4 KiB, free 434.2 MiB)
[2025-03-10T00:36:40.305+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 34.9 KiB, free 434.2 MiB)
[2025-03-10T00:36:40.313+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 27f453beda85:46799 (size: 34.9 KiB, free: 434.4 MiB)
[2025-03-10T00:36:40.316+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO SparkContext: Created broadcast 0 from csv at NativeMethodAccessorImpl.java:0
[2025-03-10T00:36:40.370+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO FileSourceScanExec: Planning scan with bin packing, max size: 4838318 bytes, open cost is considered as scanning 4194304 bytes.
[2025-03-10T00:36:40.486+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO SparkContext: Starting job: csv at NativeMethodAccessorImpl.java:0
[2025-03-10T00:36:40.500+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO DAGScheduler: Got job 0 (csv at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2025-03-10T00:36:40.500+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO DAGScheduler: Final stage: ResultStage 0 (csv at NativeMethodAccessorImpl.java:0)
[2025-03-10T00:36:40.501+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO DAGScheduler: Parents of final stage: List()
[2025-03-10T00:36:40.502+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO DAGScheduler: Missing parents: List()
[2025-03-10T00:36:40.505+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[3] at csv at NativeMethodAccessorImpl.java:0), which has no missing parents
[2025-03-10T00:36:40.604+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 13.5 KiB, free 434.2 MiB)
[2025-03-10T00:36:40.626+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 6.4 KiB, free 434.1 MiB)
[2025-03-10T00:36:40.627+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 27f453beda85:46799 (size: 6.4 KiB, free: 434.4 MiB)
[2025-03-10T00:36:40.630+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1585
[2025-03-10T00:36:40.673+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[3] at csv at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2025-03-10T00:36:40.684+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2025-03-10T00:36:40.740+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:40 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:36:41.008+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:41 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 172.19.0.6:36891 (size: 6.4 KiB, free: 1048.8 MiB)
[2025-03-10T00:36:42.026+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:42 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.19.0.6:36891 (size: 34.9 KiB, free: 1048.8 MiB)
[2025-03-10T00:36:43.127+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:36:43.128+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:36:43.129+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:36:43.129+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:36:43.129+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:36:43.129+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:36:43.130+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:36:43.130+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:36:43.130+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:36:43.131+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:36:43.131+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:36:43.131+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:36:43.131+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:36:43.132+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:36:43.132+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:36:43.132+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:36:43.132+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:36:43.132+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:36:43.132+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:36:43.133+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:36:43.133+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:36:43.133+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:36:43.133+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:36:43.133+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:36:43.133+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:36:43.133+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:36:43.134+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:36:43.134+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:36:43.138+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 1) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:36:43.201+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on 172.19.0.6, executor 0: org.apache.spark.SparkFileNotFoundException (/opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:36:43.201+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.) [duplicate 1]
[2025-03-10T00:36:43.216+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 2) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:36:43.270+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO TaskSetManager: Lost task 0.2 in stage 0.0 (TID 2) on 172.19.0.6, executor 0: org.apache.spark.SparkFileNotFoundException (/opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:36:43.270+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.) [duplicate 2]
[2025-03-10T00:36:43.270+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 3) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:36:43.327+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 3) on 172.19.0.6, executor 0: org.apache.spark.SparkFileNotFoundException (/opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:36:43.327+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.) [duplicate 3]
[2025-03-10T00:36:43.329+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
[2025-03-10T00:36:43.339+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2025-03-10T00:36:43.340+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO TaskSchedulerImpl: Cancelling stage 0
[2025-03-10T00:36:43.340+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage cancelled: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:36:43.340+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:36:43.340+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:36:43.341+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:36:43.341+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:36:43.341+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:36:43.341+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:36:43.341+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:36:43.341+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:36:43.341+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:36:43.342+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:36:43.342+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:36:43.342+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:36:43.342+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:36:43.342+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:36:43.342+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:36:43.342+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:36:43.342+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:36:43.343+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:36:43.343+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:36:43.343+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:36:43.343+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:36:43.343+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:36:43.343+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:36:43.343+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:36:43.343+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:36:43.344+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:36:43.344+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:36:43.344+0000] {spark_submit.py:641} INFO - Driver stacktrace:
[2025-03-10T00:36:43.344+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO DAGScheduler: ResultStage 0 (csv at NativeMethodAccessorImpl.java:0) failed in 2.810 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:36:43.344+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:36:43.345+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:36:43.345+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:36:43.345+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:36:43.345+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:36:43.345+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:36:43.346+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:36:43.346+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:36:43.346+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:36:43.346+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:36:43.347+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:36:43.347+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:36:43.347+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:36:43.347+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:36:43.348+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:36:43.348+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:36:43.348+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:36:43.348+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:36:43.348+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:36:43.348+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:36:43.348+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:36:43.349+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:36:43.349+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:36:43.349+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:36:43.349+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:36:43.349+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:36:43.349+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:36:43.349+0000] {spark_submit.py:641} INFO - Driver stacktrace:
[2025-03-10T00:36:43.357+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO DAGScheduler: Job 0 failed: csv at NativeMethodAccessorImpl.java:0, took 2.869402 s
[2025-03-10T00:36:43.576+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-03-10T00:36:43.577+0000] {spark_submit.py:641} INFO - File "/opt/***/jobs/gcc_test_job.py", line 11, in <module>
[2025-03-10T00:36:43.577+0000] {spark_submit.py:641} INFO - df = spark.read.csv(gcs_bucket_path, header=True)
[2025-03-10T00:36:43.578+0000] {spark_submit.py:641} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-10T00:36:43.578+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-03-10T00:36:43.578+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-10T00:36:43.578+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-03-10T00:36:43.579+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-03-10T00:36:43.641+0000] {spark_submit.py:641} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o33.csv.
[2025-03-10T00:36:43.644+0000] {spark_submit.py:641} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:36:43.645+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:36:43.646+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:36:43.647+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:36:43.648+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:36:43.649+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:36:43.650+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:36:43.651+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:36:43.652+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:36:43.653+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:36:43.654+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:36:43.654+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:36:43.655+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:36:43.656+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:36:43.656+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:36:43.657+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:36:43.658+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:36:43.658+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:36:43.659+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:36:43.659+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:36:43.660+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:36:43.660+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:36:43.661+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:36:43.661+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:36:43.661+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:36:43.662+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:36:43.662+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:36:43.663+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:36:43.663+0000] {spark_submit.py:641} INFO - Driver stacktrace:
[2025-03-10T00:36:43.663+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2025-03-10T00:36:43.664+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2025-03-10T00:36:43.664+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2025-03-10T00:36:43.665+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-03-10T00:36:43.665+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-03-10T00:36:43.665+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-03-10T00:36:43.666+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2025-03-10T00:36:43.666+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2025-03-10T00:36:43.666+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2025-03-10T00:36:43.667+0000] {spark_submit.py:641} INFO - at scala.Option.foreach(Option.scala:407)
[2025-03-10T00:36:43.667+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2025-03-10T00:36:43.667+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2025-03-10T00:36:43.668+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2025-03-10T00:36:43.668+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2025-03-10T00:36:43.669+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-03-10T00:36:43.669+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2025-03-10T00:36:43.670+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2025-03-10T00:36:43.670+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2025-03-10T00:36:43.671+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2025-03-10T00:36:43.671+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:530)
[2025-03-10T00:36:43.672+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:483)
[2025-03-10T00:36:43.672+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:61)
[2025-03-10T00:36:43.672+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:4333)
[2025-03-10T00:36:43.673+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:3316)
[2025-03-10T00:36:43.673+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:4323)
[2025-03-10T00:36:43.673+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
[2025-03-10T00:36:43.674+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:4321)
[2025-03-10T00:36:43.674+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-03-10T00:36:43.674+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-03-10T00:36:43.675+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-03-10T00:36:43.675+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-03-10T00:36:43.675+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-03-10T00:36:43.676+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4321)
[2025-03-10T00:36:43.676+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.head(Dataset.scala:3316)
[2025-03-10T00:36:43.677+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.take(Dataset.scala:3539)
[2025-03-10T00:36:43.678+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.csv.TextInputCSVDataSource$.infer(CSVDataSource.scala:111)
[2025-03-10T00:36:43.678+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.csv.CSVDataSource.inferSchema(CSVDataSource.scala:64)
[2025-03-10T00:36:43.678+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat.inferSchema(CSVFileFormat.scala:62)
[2025-03-10T00:36:43.679+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:208)
[2025-03-10T00:36:43.679+0000] {spark_submit.py:641} INFO - at scala.Option.orElse(Option.scala:447)
[2025-03-10T00:36:43.680+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:205)
[2025-03-10T00:36:43.680+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:407)
[2025-03-10T00:36:43.680+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-03-10T00:36:43.681+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-03-10T00:36:43.681+0000] {spark_submit.py:641} INFO - at scala.Option.getOrElse(Option.scala:189)
[2025-03-10T00:36:43.682+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-03-10T00:36:43.682+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:538)
[2025-03-10T00:36:43.682+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-10T00:36:43.683+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-03-10T00:36:43.683+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-10T00:36:43.684+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-03-10T00:36:43.684+0000] {spark_submit.py:641} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-10T00:36:43.684+0000] {spark_submit.py:641} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-10T00:36:43.685+0000] {spark_submit.py:641} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-10T00:36:43.685+0000] {spark_submit.py:641} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-10T00:36:43.685+0000] {spark_submit.py:641} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-10T00:36:43.686+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-10T00:36:43.687+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-10T00:36:43.687+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-10T00:36:43.688+0000] {spark_submit.py:641} INFO - Caused by: org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:36:43.688+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:36:43.688+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:36:43.689+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:36:43.689+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:36:43.690+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:36:43.690+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:36:43.690+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:36:43.691+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:36:43.691+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:36:43.692+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:36:43.692+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:36:43.693+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:36:43.693+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:36:43.694+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:36:43.694+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:36:43.694+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:36:43.695+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:36:43.695+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:36:43.696+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:36:43.696+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:36:43.697+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:36:43.697+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:36:43.697+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:36:43.698+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:36:43.698+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:36:43.699+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:36:43.699+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:36:43.722+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-10T00:36:43.723+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-10T00:36:43.735+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO SparkUI: Stopped Spark web UI at http://27f453beda85:4040
[2025-03-10T00:36:43.748+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-03-10T00:36:43.752+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-03-10T00:36:43.806+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-10T00:36:43.831+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO MemoryStore: MemoryStore cleared
[2025-03-10T00:36:43.832+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO BlockManager: BlockManager stopped
[2025-03-10T00:36:43.839+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-10T00:36:43.843+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-10T00:36:43.888+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO SparkContext: Successfully stopped SparkContext
[2025-03-10T00:36:43.892+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO ShutdownHookManager: Shutdown hook called
[2025-03-10T00:36:43.894+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-619e8fa1-ddc7-4bec-b278-2a4349c8b2f4/pyspark-4d44256b-ca9b-44c3-a842-352d623a9e5a
[2025-03-10T00:36:43.899+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-619e8fa1-ddc7-4bec-b278-2a4349c8b2f4
[2025-03-10T00:36:43.905+0000] {spark_submit.py:641} INFO - 25/03/10 00:36:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-37d8449e-ab20-4568-9283-72ef8c51604d
[2025-03-10T00:36:43.959+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py. Error code is: 1.
[2025-03-10T00:36:43.965+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=spark_gcs_job, task_id=submit_spark_gcs_job, run_id=manual__2025-03-10T00:31:02.222494+00:00, execution_date=20250310T003102, start_date=20250310T003625, end_date=20250310T003643
[2025-03-10T00:36:43.979+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-10T00:36:43.980+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 470 for task submit_spark_gcs_job (Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py. Error code is: 1.; 1695)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py. Error code is: 1.
[2025-03-10T00:36:44.008+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T00:36:44.026+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T00:36:44.028+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
