[2025-03-10T00:31:03.025+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T00:31:03.055+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-10T00:31:02.222494+00:00 [queued]>
[2025-03-10T00:31:03.066+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-10T00:31:02.222494+00:00 [queued]>
[2025-03-10T00:31:03.067+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-10T00:31:03.083+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): submit_spark_gcs_job> on 2025-03-10 00:31:02.222494+00:00
[2025-03-10T00:31:03.089+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_gcs_job', 'submit_spark_gcs_job', 'manual__2025-03-10T00:31:02.222494+00:00', '--job-id', '469', '--raw', '--subdir', 'DAGS_FOLDER/gcs_conn_test.py', '--cfg-path', '/tmp/tmpr3e0m5l4']
[2025-03-10T00:31:03.093+0000] {standard_task_runner.py:105} INFO - Job 469: Subtask submit_spark_gcs_job
[2025-03-10T00:31:03.096+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1465) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-10T00:31:03.097+0000] {standard_task_runner.py:72} INFO - Started process 1466 to run task
[2025-03-10T00:31:03.142+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-10T00:31:02.222494+00:00 [running]> on host 27f453beda85
[2025-03-10T00:31:03.269+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_gcs_job' AIRFLOW_CTX_TASK_ID='submit_spark_gcs_job' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T00:31:02.222494+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T00:31:02.222494+00:00'
[2025-03-10T00:31:03.270+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-10T00:31:03.305+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-03-10T00:31:03.309+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py
[2025-03-10T00:31:03.368+0000] {spark_submit.py:641} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-03-10T00:31:05.001+0000] {spark_submit.py:641} INFO - Using properties file: null
[2025-03-10T00:31:05.142+0000] {spark_submit.py:641} INFO - Parsed arguments:
[2025-03-10T00:31:05.143+0000] {spark_submit.py:641} INFO - master                  spark://spark:7077
[2025-03-10T00:31:05.143+0000] {spark_submit.py:641} INFO - remote                  null
[2025-03-10T00:31:05.144+0000] {spark_submit.py:641} INFO - deployMode              client
[2025-03-10T00:31:05.144+0000] {spark_submit.py:641} INFO - executorMemory          2g
[2025-03-10T00:31:05.144+0000] {spark_submit.py:641} INFO - executorCores           1
[2025-03-10T00:31:05.145+0000] {spark_submit.py:641} INFO - totalExecutorCores      null
[2025-03-10T00:31:05.145+0000] {spark_submit.py:641} INFO - propertiesFile          null
[2025-03-10T00:31:05.145+0000] {spark_submit.py:641} INFO - driverMemory            null
[2025-03-10T00:31:05.146+0000] {spark_submit.py:641} INFO - driverCores             null
[2025-03-10T00:31:05.146+0000] {spark_submit.py:641} INFO - driverExtraClassPath    null
[2025-03-10T00:31:05.146+0000] {spark_submit.py:641} INFO - driverExtraLibraryPath  null
[2025-03-10T00:31:05.146+0000] {spark_submit.py:641} INFO - driverExtraJavaOptions  null
[2025-03-10T00:31:05.147+0000] {spark_submit.py:641} INFO - supervise               false
[2025-03-10T00:31:05.147+0000] {spark_submit.py:641} INFO - queue                   null
[2025-03-10T00:31:05.147+0000] {spark_submit.py:641} INFO - numExecutors            2
[2025-03-10T00:31:05.148+0000] {spark_submit.py:641} INFO - files                   null
[2025-03-10T00:31:05.148+0000] {spark_submit.py:641} INFO - pyFiles                 null
[2025-03-10T00:31:05.148+0000] {spark_submit.py:641} INFO - archives                null
[2025-03-10T00:31:05.149+0000] {spark_submit.py:641} INFO - mainClass               null
[2025-03-10T00:31:05.149+0000] {spark_submit.py:641} INFO - primaryResource         file:/opt/***/jobs/gcc_test_job.py
[2025-03-10T00:31:05.149+0000] {spark_submit.py:641} INFO - name                    arrow-spark
[2025-03-10T00:31:05.149+0000] {spark_submit.py:641} INFO - childArgs               []
[2025-03-10T00:31:05.150+0000] {spark_submit.py:641} INFO - jars                    file:/opt/***/jars/gcs-connector-hadoop3-2.2.0.jar
[2025-03-10T00:31:05.150+0000] {spark_submit.py:641} INFO - packages                null
[2025-03-10T00:31:05.150+0000] {spark_submit.py:641} INFO - packagesExclusions      null
[2025-03-10T00:31:05.151+0000] {spark_submit.py:641} INFO - repositories            null
[2025-03-10T00:31:05.151+0000] {spark_submit.py:641} INFO - verbose                 true
[2025-03-10T00:31:05.151+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:31:05.151+0000] {spark_submit.py:641} INFO - Spark properties used, including those specified through
[2025-03-10T00:31:05.152+0000] {spark_submit.py:641} INFO - --conf and those from the properties file null:
[2025-03-10T00:31:05.152+0000] {spark_submit.py:641} INFO - (spark.executor.cores,1)
[2025-03-10T00:31:05.152+0000] {spark_submit.py:641} INFO - (spark.executor.instances,2)
[2025-03-10T00:31:05.153+0000] {spark_submit.py:641} INFO - (spark.executor.memory,2g)
[2025-03-10T00:31:05.158+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.enable,true)
[2025-03-10T00:31:05.162+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.json.keyfile,/opt/***/keys/first-key.json)
[2025-03-10T00:31:05.162+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.impl,com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem)
[2025-03-10T00:31:05.163+0000] {spark_submit.py:641} INFO - (spark.master,spark://spark:7077)
[2025-03-10T00:31:05.164+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:31:05.164+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:31:05.478+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-10T00:31:05.761+0000] {spark_submit.py:641} INFO - Main class:
[2025-03-10T00:31:05.762+0000] {spark_submit.py:641} INFO - org.apache.spark.deploy.PythonRunner
[2025-03-10T00:31:05.763+0000] {spark_submit.py:641} INFO - Arguments:
[2025-03-10T00:31:05.763+0000] {spark_submit.py:641} INFO - file:/opt/***/jobs/gcc_test_job.py
[2025-03-10T00:31:05.763+0000] {spark_submit.py:641} INFO - null
[2025-03-10T00:31:05.766+0000] {spark_submit.py:641} INFO - Spark config:
[2025-03-10T00:31:05.767+0000] {spark_submit.py:641} INFO - (spark.app.name,arrow-spark)
[2025-03-10T00:31:05.767+0000] {spark_submit.py:641} INFO - (spark.app.submitTime,1741566665726)
[2025-03-10T00:31:05.767+0000] {spark_submit.py:641} INFO - (spark.executor.cores,1)
[2025-03-10T00:31:05.768+0000] {spark_submit.py:641} INFO - (spark.executor.instances,2)
[2025-03-10T00:31:05.768+0000] {spark_submit.py:641} INFO - (spark.executor.memory,2g)
[2025-03-10T00:31:05.768+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.enable,true)
[2025-03-10T00:31:05.768+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.json.keyfile,/opt/***/keys/first-key.json)
[2025-03-10T00:31:05.769+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.impl,com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem)
[2025-03-10T00:31:05.769+0000] {spark_submit.py:641} INFO - (spark.jars,file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar)
[2025-03-10T00:31:05.769+0000] {spark_submit.py:641} INFO - (spark.master,spark://spark:7077)
[2025-03-10T00:31:05.770+0000] {spark_submit.py:641} INFO - (spark.repl.local.jars,file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar)
[2025-03-10T00:31:05.770+0000] {spark_submit.py:641} INFO - (spark.submit.deployMode,client)
[2025-03-10T00:31:05.770+0000] {spark_submit.py:641} INFO - (spark.submit.pyFiles,)
[2025-03-10T00:31:05.771+0000] {spark_submit.py:641} INFO - Classpath elements:
[2025-03-10T00:31:05.772+0000] {spark_submit.py:641} INFO - file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar
[2025-03-10T00:31:05.772+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:31:05.773+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:31:06.978+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:06 INFO SparkContext: Running Spark version 3.5.5
[2025-03-10T00:31:06.981+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:06 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-03-10T00:31:06.982+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:06 INFO SparkContext: Java version 17.0.14
[2025-03-10T00:31:07.029+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO ResourceUtils: ==============================================================
[2025-03-10T00:31:07.031+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-10T00:31:07.031+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO ResourceUtils: ==============================================================
[2025-03-10T00:31:07.032+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO SparkContext: Submitted application: GCSConnectorTest
[2025-03-10T00:31:07.057+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 2048, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-10T00:31:07.073+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2025-03-10T00:31:07.076+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-10T00:31:07.138+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO SecurityManager: Changing view acls to: ***
[2025-03-10T00:31:07.141+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO SecurityManager: Changing modify acls to: ***
[2025-03-10T00:31:07.143+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO SecurityManager: Changing view acls groups to:
[2025-03-10T00:31:07.144+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO SecurityManager: Changing modify acls groups to:
[2025-03-10T00:31:07.144+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-03-10T00:31:07.379+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO Utils: Successfully started service 'sparkDriver' on port 38239.
[2025-03-10T00:31:07.415+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO SparkEnv: Registering MapOutputTracker
[2025-03-10T00:31:07.466+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-10T00:31:07.494+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-10T00:31:07.495+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-10T00:31:07.499+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-10T00:31:07.528+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-85e0c712-c162-49e2-b231-461733f59bf8
[2025-03-10T00:31:07.550+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-10T00:31:07.618+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-10T00:31:07.747+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-10T00:31:07.848+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-10T00:31:07.909+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:07 INFO SparkContext: Added JAR file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar at spark://27f453beda85:38239/jars/gcs-connector-hadoop3-2.2.0.jar with timestamp 1741566666960
[2025-03-10T00:31:08.022+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2025-03-10T00:31:08.080+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO TransportClientFactory: Successfully created connection to spark/172.19.0.5:7077 after 32 ms (0 ms spent in bootstraps)
[2025-03-10T00:31:08.213+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250310003108-0002
[2025-03-10T00:31:08.229+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250310003108-0002/0 on worker-20250310001523-172.19.0.6-39949 (172.19.0.6:39949) with 1 core(s)
[2025-03-10T00:31:08.232+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO StandaloneSchedulerBackend: Granted executor ID app-20250310003108-0002/0 on hostPort 172.19.0.6:39949 with 1 core(s), 2.0 GiB RAM
[2025-03-10T00:31:08.240+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42243.
[2025-03-10T00:31:08.241+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO NettyBlockTransferService: Server created on 27f453beda85:42243
[2025-03-10T00:31:08.244+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-10T00:31:08.255+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 27f453beda85, 42243, None)
[2025-03-10T00:31:08.261+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO BlockManagerMasterEndpoint: Registering block manager 27f453beda85:42243 with 434.4 MiB RAM, BlockManagerId(driver, 27f453beda85, 42243, None)
[2025-03-10T00:31:08.266+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 27f453beda85, 42243, None)
[2025-03-10T00:31:08.269+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 27f453beda85, 42243, None)
[2025-03-10T00:31:08.415+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250310003108-0002/0 is now RUNNING
[2025-03-10T00:31:08.872+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:08 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-10T00:31:09.268+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:09 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-10T00:31:09.278+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:09 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2025-03-10T00:31:14.722+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:14 INFO InMemoryFileIndex: It took 173 ms to list leaf files for 1 paths.
[2025-03-10T00:31:14.999+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:14 INFO InMemoryFileIndex: It took 93 ms to list leaf files for 1 paths.
[2025-03-10T00:31:16.297+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:16 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.19.0.6:38008) with ID 0,  ResourceProfileId 0
[2025-03-10T00:31:16.571+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:16 INFO BlockManagerMasterEndpoint: Registering block manager 172.19.0.6:44629 with 1048.8 MiB RAM, BlockManagerId(0, 172.19.0.6, 44629, None)
[2025-03-10T00:31:19.034+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:19 INFO FileSourceStrategy: Pushed Filters:
[2025-03-10T00:31:19.039+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:19 INFO FileSourceStrategy: Post-Scan Filters: (length(trim(value#0, None)) > 0)
[2025-03-10T00:31:19.810+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:19 INFO CodeGenerator: Code generated in 319.497616 ms
[2025-03-10T00:31:19.917+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:19 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 201.4 KiB, free 434.2 MiB)
[2025-03-10T00:31:20.052+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 34.9 KiB, free 434.2 MiB)
[2025-03-10T00:31:20.058+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 27f453beda85:42243 (size: 34.9 KiB, free: 434.4 MiB)
[2025-03-10T00:31:20.063+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO SparkContext: Created broadcast 0 from csv at NativeMethodAccessorImpl.java:0
[2025-03-10T00:31:20.076+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO FileSourceScanExec: Planning scan with bin packing, max size: 4838318 bytes, open cost is considered as scanning 4194304 bytes.
[2025-03-10T00:31:20.183+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO SparkContext: Starting job: csv at NativeMethodAccessorImpl.java:0
[2025-03-10T00:31:20.200+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO DAGScheduler: Got job 0 (csv at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2025-03-10T00:31:20.201+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO DAGScheduler: Final stage: ResultStage 0 (csv at NativeMethodAccessorImpl.java:0)
[2025-03-10T00:31:20.202+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO DAGScheduler: Parents of final stage: List()
[2025-03-10T00:31:20.216+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO DAGScheduler: Missing parents: List()
[2025-03-10T00:31:20.225+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[3] at csv at NativeMethodAccessorImpl.java:0), which has no missing parents
[2025-03-10T00:31:20.329+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 13.5 KiB, free 434.2 MiB)
[2025-03-10T00:31:20.391+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 6.4 KiB, free 434.1 MiB)
[2025-03-10T00:31:20.397+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 27f453beda85:42243 (size: 6.4 KiB, free: 434.4 MiB)
[2025-03-10T00:31:20.398+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1585
[2025-03-10T00:31:20.425+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[3] at csv at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2025-03-10T00:31:20.428+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2025-03-10T00:31:20.476+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:31:20.845+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:20 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 172.19.0.6:44629 (size: 6.4 KiB, free: 1048.8 MiB)
[2025-03-10T00:31:22.216+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:22 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.19.0.6:44629 (size: 34.9 KiB, free: 1048.8 MiB)
[2025-03-10T00:31:23.616+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:31:23.617+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:31:23.617+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:31:23.617+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:31:23.618+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:31:23.618+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:31:23.618+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:31:23.618+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:31:23.619+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:31:23.619+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:31:23.619+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:31:23.620+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:31:23.620+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:31:23.620+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:31:23.620+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:31:23.621+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:31:23.621+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:31:23.621+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:31:23.622+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:31:23.622+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:31:23.622+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:31:23.622+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:31:23.623+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:31:23.623+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:31:23.623+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:31:23.624+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:31:23.624+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:31:23.624+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:31:23.631+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 1) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:31:23.760+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on 172.19.0.6, executor 0: org.apache.spark.SparkFileNotFoundException (/opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:31:23.761+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.) [duplicate 1]
[2025-03-10T00:31:23.772+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 2) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:31:23.834+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 INFO TaskSetManager: Lost task 0.2 in stage 0.0 (TID 2) on 172.19.0.6, executor 0: org.apache.spark.SparkFileNotFoundException (/opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:31:23.836+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.) [duplicate 2]
[2025-03-10T00:31:23.840+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 3) (172.19.0.6, executor 0, partition 0, PROCESS_LOCAL, 9801 bytes)
[2025-03-10T00:31:23.906+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 3) on 172.19.0.6, executor 0: org.apache.spark.SparkFileNotFoundException (/opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:31:23.907+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.) [duplicate 3]
[2025-03-10T00:31:23.910+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
[2025-03-10T00:31:23.915+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2025-03-10T00:31:23.919+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 INFO TaskSchedulerImpl: Cancelling stage 0
[2025-03-10T00:31:23.919+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage cancelled: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:31:23.919+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:31:23.920+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:31:23.920+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:31:23.920+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:31:23.920+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:31:23.920+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:31:23.921+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:31:23.921+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:31:23.921+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:31:23.921+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:31:23.921+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:31:23.921+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:31:23.921+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:31:23.922+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:31:23.922+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:31:23.922+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:31:23.922+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:31:23.922+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:31:23.922+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:31:23.922+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:31:23.922+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:31:23.923+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:31:23.923+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:31:23.923+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:31:23.923+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:31:23.923+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:31:23.923+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:31:23.923+0000] {spark_submit.py:641} INFO - Driver stacktrace:
[2025-03-10T00:31:23.924+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 INFO DAGScheduler: ResultStage 0 (csv at NativeMethodAccessorImpl.java:0) failed in 3.675 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:31:23.924+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:31:23.924+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:31:23.924+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:31:23.924+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:31:23.924+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:31:23.924+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:31:23.925+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:31:23.925+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:31:23.925+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:31:23.925+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:31:23.925+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:31:23.925+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:31:23.925+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:31:23.925+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:31:23.926+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:31:23.926+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:31:23.926+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:31:23.926+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:31:23.926+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:31:23.926+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:31:23.926+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:31:23.927+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:31:23.927+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:31:23.927+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:31:23.927+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:31:23.927+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:31:23.927+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:31:23.927+0000] {spark_submit.py:641} INFO - Driver stacktrace:
[2025-03-10T00:31:23.946+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:23 INFO DAGScheduler: Job 0 failed: csv at NativeMethodAccessorImpl.java:0, took 3.749010 s
[2025-03-10T00:31:24.196+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-03-10T00:31:24.197+0000] {spark_submit.py:641} INFO - File "/opt/***/jobs/gcc_test_job.py", line 11, in <module>
[2025-03-10T00:31:24.197+0000] {spark_submit.py:641} INFO - df = spark.read.csv(gcs_bucket_path, header=True)
[2025-03-10T00:31:24.197+0000] {spark_submit.py:641} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-10T00:31:24.198+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-03-10T00:31:24.198+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-10T00:31:24.198+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-03-10T00:31:24.198+0000] {spark_submit.py:641} INFO - File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-03-10T00:31:24.252+0000] {spark_submit.py:641} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o33.csv.
[2025-03-10T00:31:24.253+0000] {spark_submit.py:641} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 0): org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:31:24.253+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:31:24.253+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:31:24.254+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:31:24.254+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:31:24.254+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:31:24.255+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:31:24.255+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:31:24.255+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:31:24.256+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:31:24.256+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:31:24.256+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:31:24.257+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:31:24.257+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:31:24.257+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:31:24.257+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:31:24.258+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:31:24.258+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:31:24.258+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:31:24.259+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:31:24.259+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:31:24.259+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:31:24.259+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:31:24.260+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:31:24.260+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:31:24.260+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:31:24.261+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:31:24.261+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:31:24.261+0000] {spark_submit.py:641} INFO - Driver stacktrace:
[2025-03-10T00:31:24.261+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2025-03-10T00:31:24.262+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2025-03-10T00:31:24.262+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2025-03-10T00:31:24.262+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-03-10T00:31:24.263+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-03-10T00:31:24.263+0000] {spark_submit.py:641} INFO - at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-03-10T00:31:24.263+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2025-03-10T00:31:24.263+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2025-03-10T00:31:24.263+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2025-03-10T00:31:24.264+0000] {spark_submit.py:641} INFO - at scala.Option.foreach(Option.scala:407)
[2025-03-10T00:31:24.264+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2025-03-10T00:31:24.264+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2025-03-10T00:31:24.264+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2025-03-10T00:31:24.264+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2025-03-10T00:31:24.265+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2025-03-10T00:31:24.265+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2025-03-10T00:31:24.265+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2025-03-10T00:31:24.265+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2025-03-10T00:31:24.265+0000] {spark_submit.py:641} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2025-03-10T00:31:24.265+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:530)
[2025-03-10T00:31:24.266+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:483)
[2025-03-10T00:31:24.266+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:61)
[2025-03-10T00:31:24.266+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:4333)
[2025-03-10T00:31:24.266+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:3316)
[2025-03-10T00:31:24.266+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:4323)
[2025-03-10T00:31:24.266+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
[2025-03-10T00:31:24.266+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:4321)
[2025-03-10T00:31:24.266+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2025-03-10T00:31:24.267+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2025-03-10T00:31:24.267+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2025-03-10T00:31:24.267+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2025-03-10T00:31:24.267+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2025-03-10T00:31:24.267+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4321)
[2025-03-10T00:31:24.267+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.head(Dataset.scala:3316)
[2025-03-10T00:31:24.267+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.Dataset.take(Dataset.scala:3539)
[2025-03-10T00:31:24.267+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.csv.TextInputCSVDataSource$.infer(CSVDataSource.scala:111)
[2025-03-10T00:31:24.268+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.csv.CSVDataSource.inferSchema(CSVDataSource.scala:64)
[2025-03-10T00:31:24.268+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat.inferSchema(CSVFileFormat.scala:62)
[2025-03-10T00:31:24.268+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:208)
[2025-03-10T00:31:24.268+0000] {spark_submit.py:641} INFO - at scala.Option.orElse(Option.scala:447)
[2025-03-10T00:31:24.268+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:205)
[2025-03-10T00:31:24.268+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:407)
[2025-03-10T00:31:24.268+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-03-10T00:31:24.268+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-03-10T00:31:24.268+0000] {spark_submit.py:641} INFO - at scala.Option.getOrElse(Option.scala:189)
[2025-03-10T00:31:24.269+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-03-10T00:31:24.269+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:538)
[2025-03-10T00:31:24.269+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-10T00:31:24.269+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-03-10T00:31:24.269+0000] {spark_submit.py:641} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-10T00:31:24.269+0000] {spark_submit.py:641} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-03-10T00:31:24.269+0000] {spark_submit.py:641} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-10T00:31:24.269+0000] {spark_submit.py:641} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-10T00:31:24.269+0000] {spark_submit.py:641} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-10T00:31:24.269+0000] {spark_submit.py:641} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-10T00:31:24.270+0000] {spark_submit.py:641} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-10T00:31:24.270+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-10T00:31:24.270+0000] {spark_submit.py:641} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-10T00:31:24.270+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-10T00:31:24.270+0000] {spark_submit.py:641} INFO - Caused by: org.apache.spark.SparkFileNotFoundException: /opt/***/keys/first-key.json (No such file or directory)
[2025-03-10T00:31:24.270+0000] {spark_submit.py:641} INFO - It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
[2025-03-10T00:31:24.270+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.readCurrentFileNotFoundError(QueryExecutionErrors.scala:781)
[2025-03-10T00:31:24.270+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:222)
[2025-03-10T00:31:24.271+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:282)
[2025-03-10T00:31:24.271+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:131)
[2025-03-10T00:31:24.271+0000] {spark_submit.py:641} INFO - at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
[2025-03-10T00:31:24.271+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
[2025-03-10T00:31:24.271+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[2025-03-10T00:31:24.271+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.WholeStageCodegenEvaluatorFactory$WholeStageCodegenPartitionEvaluator$$anon$1.hasNext(WholeStageCodegenEvaluatorFactory.scala:43)
[2025-03-10T00:31:24.271+0000] {spark_submit.py:641} INFO - at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
[2025-03-10T00:31:24.272+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:893)
[2025-03-10T00:31:24.272+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:893)
[2025-03-10T00:31:24.272+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
[2025-03-10T00:31:24.272+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
[2025-03-10T00:31:24.272+0000] {spark_submit.py:641} INFO - at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
[2025-03-10T00:31:24.272+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:93)
[2025-03-10T00:31:24.272+0000] {spark_submit.py:641} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:166)
[2025-03-10T00:31:24.272+0000] {spark_submit.py:641} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:141)
[2025-03-10T00:31:24.273+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:620)
[2025-03-10T00:31:24.273+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:64)
[2025-03-10T00:31:24.273+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:61)
[2025-03-10T00:31:24.273+0000] {spark_submit.py:641} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:94)
[2025-03-10T00:31:24.273+0000] {spark_submit.py:641} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:623)
[2025-03-10T00:31:24.273+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-03-10T00:31:24.273+0000] {spark_submit.py:641} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-03-10T00:31:24.274+0000] {spark_submit.py:641} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-03-10T00:31:24.274+0000] {spark_submit.py:641} INFO - 
[2025-03-10T00:31:24.311+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-10T00:31:24.312+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-10T00:31:24.322+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO SparkUI: Stopped Spark web UI at http://27f453beda85:4040
[2025-03-10T00:31:24.327+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-03-10T00:31:24.334+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-03-10T00:31:24.382+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-10T00:31:24.402+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO MemoryStore: MemoryStore cleared
[2025-03-10T00:31:24.403+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO BlockManager: BlockManager stopped
[2025-03-10T00:31:24.412+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-10T00:31:24.419+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-10T00:31:24.446+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO SparkContext: Successfully stopped SparkContext
[2025-03-10T00:31:24.447+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO ShutdownHookManager: Shutdown hook called
[2025-03-10T00:31:24.447+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-2aeecda3-df49-4824-8c2a-3bd61b3566ca/pyspark-bc5dbd5f-ed29-4908-8705-133d163b8aa2
[2025-03-10T00:31:24.460+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-2aeecda3-df49-4824-8c2a-3bd61b3566ca
[2025-03-10T00:31:24.473+0000] {spark_submit.py:641} INFO - 25/03/10 00:31:24 INFO ShutdownHookManager: Deleting directory /tmp/spark-7bf182cf-18bf-4cbd-bc9e-5b73080c023f
[2025-03-10T00:31:24.520+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py. Error code is: 1.
[2025-03-10T00:31:24.529+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_gcs_job, task_id=submit_spark_gcs_job, run_id=manual__2025-03-10T00:31:02.222494+00:00, execution_date=20250310T003102, start_date=20250310T003103, end_date=20250310T003124
[2025-03-10T00:31:24.550+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-10T00:31:24.551+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 469 for task submit_spark_gcs_job (Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py. Error code is: 1.; 1466)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py. Error code is: 1.
[2025-03-10T00:31:24.571+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T00:31:24.593+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T00:31:24.596+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
