[2025-03-09T23:30:31.385+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T23:30:31.414+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-09T23:30:30.057279+00:00 [queued]>
[2025-03-09T23:30:31.424+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-09T23:30:30.057279+00:00 [queued]>
[2025-03-09T23:30:31.425+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-09T23:30:31.439+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): submit_spark_gcs_job> on 2025-03-09 23:30:30.057279+00:00
[2025-03-09T23:30:31.446+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spark_gcs_job', 'submit_spark_gcs_job', 'manual__2025-03-09T23:30:30.057279+00:00', '--job-id', '429', '--raw', '--subdir', 'DAGS_FOLDER/gcs_conn_test.py', '--cfg-path', '/tmp/tmp9s5gauil']
[2025-03-09T23:30:31.448+0000] {standard_task_runner.py:105} INFO - Job 429: Subtask submit_spark_gcs_job
[2025-03-09T23:30:31.449+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1683) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-09T23:30:31.449+0000] {standard_task_runner.py:72} INFO - Started process 1684 to run task
[2025-03-09T23:30:31.490+0000] {task_command.py:467} INFO - Running <TaskInstance: spark_gcs_job.submit_spark_gcs_job manual__2025-03-09T23:30:30.057279+00:00 [running]> on host 27f453beda85
[2025-03-09T23:30:31.583+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_gcs_job' AIRFLOW_CTX_TASK_ID='submit_spark_gcs_job' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T23:30:30.057279+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T23:30:30.057279+00:00'
[2025-03-09T23:30:31.583+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-09T23:30:31.630+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-03-09T23:30:31.631+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --conf spark.executor.memory=2g --conf spark.executor.cores=1 --conf spark.executor.instances=2 --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.gs.auth.service.account.enable=true --conf spark.hadoop.fs.gs.auth.service.account.json.keyfile=/opt/***/keys/first-key.json --jars /opt/***/jars/gcs-connector-hadoop3-2.2.0.jar --name arrow-spark --verbose --deploy-mode client /opt/***/jobs/gcc_test_job.py
[2025-03-09T23:30:31.766+0000] {spark_submit.py:641} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-03-09T23:30:33.796+0000] {spark_submit.py:641} INFO - Using properties file: null
[2025-03-09T23:30:33.937+0000] {spark_submit.py:641} INFO - Parsed arguments:
[2025-03-09T23:30:33.937+0000] {spark_submit.py:641} INFO - master                  spark://spark:7077
[2025-03-09T23:30:33.937+0000] {spark_submit.py:641} INFO - remote                  null
[2025-03-09T23:30:33.937+0000] {spark_submit.py:641} INFO - deployMode              client
[2025-03-09T23:30:33.937+0000] {spark_submit.py:641} INFO - executorMemory          2g
[2025-03-09T23:30:33.937+0000] {spark_submit.py:641} INFO - executorCores           1
[2025-03-09T23:30:33.937+0000] {spark_submit.py:641} INFO - totalExecutorCores      null
[2025-03-09T23:30:33.938+0000] {spark_submit.py:641} INFO - propertiesFile          null
[2025-03-09T23:30:33.938+0000] {spark_submit.py:641} INFO - driverMemory            null
[2025-03-09T23:30:33.938+0000] {spark_submit.py:641} INFO - driverCores             null
[2025-03-09T23:30:33.938+0000] {spark_submit.py:641} INFO - driverExtraClassPath    null
[2025-03-09T23:30:33.938+0000] {spark_submit.py:641} INFO - driverExtraLibraryPath  null
[2025-03-09T23:30:33.938+0000] {spark_submit.py:641} INFO - driverExtraJavaOptions  null
[2025-03-09T23:30:33.938+0000] {spark_submit.py:641} INFO - supervise               false
[2025-03-09T23:30:33.938+0000] {spark_submit.py:641} INFO - queue                   null
[2025-03-09T23:30:33.938+0000] {spark_submit.py:641} INFO - numExecutors            2
[2025-03-09T23:30:33.938+0000] {spark_submit.py:641} INFO - files                   null
[2025-03-09T23:30:33.939+0000] {spark_submit.py:641} INFO - pyFiles                 null
[2025-03-09T23:30:33.939+0000] {spark_submit.py:641} INFO - archives                null
[2025-03-09T23:30:33.939+0000] {spark_submit.py:641} INFO - mainClass               null
[2025-03-09T23:30:33.939+0000] {spark_submit.py:641} INFO - primaryResource         file:/opt/***/jobs/gcc_test_job.py
[2025-03-09T23:30:33.939+0000] {spark_submit.py:641} INFO - name                    arrow-spark
[2025-03-09T23:30:33.939+0000] {spark_submit.py:641} INFO - childArgs               []
[2025-03-09T23:30:33.939+0000] {spark_submit.py:641} INFO - jars                    file:/opt/***/jars/gcs-connector-hadoop3-2.2.0.jar
[2025-03-09T23:30:33.940+0000] {spark_submit.py:641} INFO - packages                null
[2025-03-09T23:30:33.940+0000] {spark_submit.py:641} INFO - packagesExclusions      null
[2025-03-09T23:30:33.940+0000] {spark_submit.py:641} INFO - repositories            null
[2025-03-09T23:30:33.940+0000] {spark_submit.py:641} INFO - verbose                 true
[2025-03-09T23:30:33.940+0000] {spark_submit.py:641} INFO - 
[2025-03-09T23:30:33.940+0000] {spark_submit.py:641} INFO - Spark properties used, including those specified through
[2025-03-09T23:30:33.940+0000] {spark_submit.py:641} INFO - --conf and those from the properties file null:
[2025-03-09T23:30:33.940+0000] {spark_submit.py:641} INFO - (spark.executor.cores,1)
[2025-03-09T23:30:33.941+0000] {spark_submit.py:641} INFO - (spark.executor.instances,2)
[2025-03-09T23:30:33.941+0000] {spark_submit.py:641} INFO - (spark.executor.memory,2g)
[2025-03-09T23:30:33.941+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.enable,true)
[2025-03-09T23:30:33.941+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.json.keyfile,/opt/***/keys/first-key.json)
[2025-03-09T23:30:33.941+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.impl,com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem)
[2025-03-09T23:30:33.941+0000] {spark_submit.py:641} INFO - (spark.master,spark://spark:7077)
[2025-03-09T23:30:33.942+0000] {spark_submit.py:641} INFO - 
[2025-03-09T23:30:33.942+0000] {spark_submit.py:641} INFO - 
[2025-03-09T23:30:34.400+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-09T23:30:34.608+0000] {spark_submit.py:641} INFO - Main class:
[2025-03-09T23:30:34.608+0000] {spark_submit.py:641} INFO - org.apache.spark.deploy.PythonRunner
[2025-03-09T23:30:34.608+0000] {spark_submit.py:641} INFO - Arguments:
[2025-03-09T23:30:34.609+0000] {spark_submit.py:641} INFO - file:/opt/***/jobs/gcc_test_job.py
[2025-03-09T23:30:34.609+0000] {spark_submit.py:641} INFO - null
[2025-03-09T23:30:34.610+0000] {spark_submit.py:641} INFO - Spark config:
[2025-03-09T23:30:34.610+0000] {spark_submit.py:641} INFO - (spark.app.name,arrow-spark)
[2025-03-09T23:30:34.610+0000] {spark_submit.py:641} INFO - (spark.app.submitTime,1741563034597)
[2025-03-09T23:30:34.610+0000] {spark_submit.py:641} INFO - (spark.executor.cores,1)
[2025-03-09T23:30:34.611+0000] {spark_submit.py:641} INFO - (spark.executor.instances,2)
[2025-03-09T23:30:34.611+0000] {spark_submit.py:641} INFO - (spark.executor.memory,2g)
[2025-03-09T23:30:34.611+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.enable,true)
[2025-03-09T23:30:34.611+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.auth.service.account.json.keyfile,/opt/***/keys/first-key.json)
[2025-03-09T23:30:34.611+0000] {spark_submit.py:641} INFO - (spark.hadoop.fs.gs.impl,com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem)
[2025-03-09T23:30:34.611+0000] {spark_submit.py:641} INFO - (spark.jars,file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar)
[2025-03-09T23:30:34.611+0000] {spark_submit.py:641} INFO - (spark.master,spark://spark:7077)
[2025-03-09T23:30:34.611+0000] {spark_submit.py:641} INFO - (spark.repl.local.jars,file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar)
[2025-03-09T23:30:34.611+0000] {spark_submit.py:641} INFO - (spark.submit.deployMode,client)
[2025-03-09T23:30:34.611+0000] {spark_submit.py:641} INFO - (spark.submit.pyFiles,)
[2025-03-09T23:30:34.612+0000] {spark_submit.py:641} INFO - Classpath elements:
[2025-03-09T23:30:34.612+0000] {spark_submit.py:641} INFO - file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar
[2025-03-09T23:30:34.612+0000] {spark_submit.py:641} INFO - 
[2025-03-09T23:30:34.612+0000] {spark_submit.py:641} INFO - 
[2025-03-09T23:30:36.309+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO SparkContext: Running Spark version 3.5.5
[2025-03-09T23:30:36.310+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-03-09T23:30:36.310+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO SparkContext: Java version 17.0.14
[2025-03-09T23:30:36.358+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO ResourceUtils: ==============================================================
[2025-03-09T23:30:36.358+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-09T23:30:36.359+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO ResourceUtils: ==============================================================
[2025-03-09T23:30:36.361+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO SparkContext: Submitted application: GCSConnectorTest
[2025-03-09T23:30:36.413+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 2048, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-09T23:30:36.427+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO ResourceProfile: Limiting resource is cpus at 1 tasks per executor
[2025-03-09T23:30:36.429+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-09T23:30:36.641+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO SecurityManager: Changing view acls to: ***
[2025-03-09T23:30:36.642+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO SecurityManager: Changing modify acls to: ***
[2025-03-09T23:30:36.642+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO SecurityManager: Changing view acls groups to:
[2025-03-09T23:30:36.643+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO SecurityManager: Changing modify acls groups to:
[2025-03-09T23:30:36.643+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:36 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-03-09T23:30:37.115+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO Utils: Successfully started service 'sparkDriver' on port 40801.
[2025-03-09T23:30:37.160+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO SparkEnv: Registering MapOutputTracker
[2025-03-09T23:30:37.204+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-09T23:30:37.227+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-09T23:30:37.228+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-09T23:30:37.232+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-09T23:30:37.262+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-64ad1c42-1a30-46b2-b3f8-03ef72d92019
[2025-03-09T23:30:37.279+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-09T23:30:37.296+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-09T23:30:37.506+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-09T23:30:37.627+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-09T23:30:37.680+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO SparkContext: Added JAR file:///opt/***/jars/gcs-connector-hadoop3-2.2.0.jar at spark://27f453beda85:40801/jars/gcs-connector-hadoop3-2.2.0.jar with timestamp 1741563036271
[2025-03-09T23:30:37.802+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2025-03-09T23:30:37.875+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO TransportClientFactory: Successfully created connection to spark/172.19.0.5:7077 after 38 ms (0 ms spent in bootstraps)
[2025-03-09T23:30:37.984+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:37 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250309233037-0001
[2025-03-09T23:30:38.003+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33833.
[2025-03-09T23:30:38.004+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO NettyBlockTransferService: Server created on 27f453beda85:33833
[2025-03-09T23:30:38.009+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-09T23:30:38.029+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 27f453beda85, 33833, None)
[2025-03-09T23:30:38.032+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO BlockManagerMasterEndpoint: Registering block manager 27f453beda85:33833 with 434.4 MiB RAM, BlockManagerId(driver, 27f453beda85, 33833, None)
[2025-03-09T23:30:38.034+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 27f453beda85, 33833, None)
[2025-03-09T23:30:38.037+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 27f453beda85, 33833, None)
[2025-03-09T23:30:38.064+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250309233037-0001/0 on worker-20250309233004-172.19.0.6-44019 (172.19.0.6:44019) with 1 core(s)
[2025-03-09T23:30:38.074+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO StandaloneSchedulerBackend: Granted executor ID app-20250309233037-0001/0 on hostPort 172.19.0.6:44019 with 1 core(s), 2.0 GiB RAM
[2025-03-09T23:30:38.074+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250309233037-0001/1 on worker-20250309233004-172.19.0.6-44019 (172.19.0.6:44019) with 1 core(s)
[2025-03-09T23:30:38.075+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO StandaloneSchedulerBackend: Granted executor ID app-20250309233037-0001/1 on hostPort 172.19.0.6:44019 with 1 core(s), 2.0 GiB RAM
[2025-03-09T23:30:38.546+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250309233037-0001/1 is now RUNNING
[2025-03-09T23:30:38.564+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250309233037-0001/0 is now RUNNING
[2025-03-09T23:30:38.599+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:38 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-09T23:30:39.031+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:39 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-09T23:30:39.039+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:39 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2025-03-09T23:30:45.397+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:45 INFO InMemoryFileIndex: It took 261 ms to list leaf files for 1 paths.
[2025-03-09T23:30:45.860+0000] {spark_submit.py:641} INFO - 25/03/09 23:30:45 INFO InMemoryFileIndex: It took 100 ms to list leaf files for 1 paths.
[2025-03-09T23:32:16.688+0000] {job.py:229} INFO - Heartbeat recovered after 83.56 seconds
[2025-03-09T23:32:17.071+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@3c9c1372)) by listener AppStatusListener took 1.505274362s.
[2025-03-09T23:32:17.112+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250309233037-0001/1 is now LOST (worker lost: Not receiving heartbeat for 60 seconds)
[2025-03-09T23:32:17.113+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneSchedulerBackend: Executor app-20250309233037-0001/1 removed: worker lost: Not receiving heartbeat for 60 seconds
[2025-03-09T23:32:17.175+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250309233037-0001/0 is now LOST (worker lost: Not receiving heartbeat for 60 seconds)
[2025-03-09T23:32:17.176+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneSchedulerBackend: Executor app-20250309233037-0001/0 removed: worker lost: Not receiving heartbeat for 60 seconds
[2025-03-09T23:32:17.367+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneAppClient$ClientEndpoint: Master removed worker worker-20250309233004-172.19.0.6-44019: Not receiving heartbeat for 60 seconds
[2025-03-09T23:32:17.368+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneSchedulerBackend: Worker worker-20250309233004-172.19.0.6-44019 removed: Not receiving heartbeat for 60 seconds
[2025-03-09T23:32:17.409+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO BlockManagerMaster: Removal of executor 1 requested
[2025-03-09T23:32:17.413+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250309233037-0001/2 on worker-20250309233004-172.19.0.6-44019 (172.19.0.6:44019) with 1 core(s)
[2025-03-09T23:32:17.445+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneSchedulerBackend: Granted executor ID app-20250309233037-0001/2 on hostPort 172.19.0.6:44019 with 1 core(s), 2.0 GiB RAM
[2025-03-09T23:32:17.485+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asked to remove non-existent executor 1
[2025-03-09T23:32:17.500+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250309233037-0001/3 on worker-20250309233004-172.19.0.6-44019 (172.19.0.6:44019) with 1 core(s)
[2025-03-09T23:32:17.500+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneSchedulerBackend: Granted executor ID app-20250309233037-0001/3 on hostPort 172.19.0.6:44019 with 1 core(s), 2.0 GiB RAM
[2025-03-09T23:32:17.514+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO BlockManagerMaster: Removal of executor 0 requested
[2025-03-09T23:32:17.515+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asked to remove non-existent executor 0
[2025-03-09T23:32:17.545+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO TaskSchedulerImpl: Handle removed worker worker-20250309233004-172.19.0.6-44019: Not receiving heartbeat for 60 seconds
[2025-03-09T23:32:17.579+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO BlockManagerMasterEndpoint: Trying to remove executor 1 from BlockManagerMaster.
[2025-03-09T23:32:17.580+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO BlockManagerMasterEndpoint: Trying to remove executor 0 from BlockManagerMaster.
[2025-03-09T23:32:17.665+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO DAGScheduler: Shuffle files lost for worker worker-20250309233004-172.19.0.6-44019 on host 172.19.0.6
[2025-03-09T23:32:17.832+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250309233037-0001/2 is now RUNNING
[2025-03-09T23:32:17.846+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:17 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250309233037-0001/3 is now RUNNING
[2025-03-09T23:32:22.247+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:22 INFO FileSourceStrategy: Pushed Filters:
[2025-03-09T23:32:22.266+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:22 INFO FileSourceStrategy: Post-Scan Filters: (length(trim(value#0, None)) > 0)
[2025-03-09T23:32:25.135+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:25 INFO CodeGenerator: Code generated in 923.46082 ms
[2025-03-09T23:32:25.450+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:25 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 201.4 KiB, free 434.2 MiB)
[2025-03-09T23:32:25.874+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:25 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 34.9 KiB, free 434.2 MiB)
[2025-03-09T23:32:25.885+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:25 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 27f453beda85:33833 (size: 34.9 KiB, free: 434.4 MiB)
[2025-03-09T23:32:25.936+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:25 INFO SparkContext: Created broadcast 0 from csv at NativeMethodAccessorImpl.java:0
[2025-03-09T23:32:26.013+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:26 INFO FileSourceScanExec: Planning scan with bin packing, max size: 4838318 bytes, open cost is considered as scanning 4194304 bytes.
[2025-03-09T23:32:26.617+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:26 INFO SparkContext: Starting job: csv at NativeMethodAccessorImpl.java:0
[2025-03-09T23:32:26.692+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:26 INFO DAGScheduler: Got job 0 (csv at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2025-03-09T23:32:26.694+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:26 INFO DAGScheduler: Final stage: ResultStage 0 (csv at NativeMethodAccessorImpl.java:0)
[2025-03-09T23:32:26.696+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:26 INFO DAGScheduler: Parents of final stage: List()
[2025-03-09T23:32:26.705+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:26 INFO DAGScheduler: Missing parents: List()
[2025-03-09T23:32:26.726+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:26 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[3] at csv at NativeMethodAccessorImpl.java:0), which has no missing parents
[2025-03-09T23:32:27.053+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:27 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 13.5 KiB, free 434.2 MiB)
[2025-03-09T23:32:27.067+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:27 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 6.4 KiB, free 434.1 MiB)
[2025-03-09T23:32:27.068+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:27 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 27f453beda85:33833 (size: 6.4 KiB, free: 434.4 MiB)
[2025-03-09T23:32:27.073+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:27 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1585
[2025-03-09T23:32:27.146+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:27 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[3] at csv at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2025-03-09T23:32:27.150+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:27 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2025-03-09T23:32:43.261+0000] {spark_submit.py:641} INFO - 25/03/09 23:32:43 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:32:47.104+0000] {job.py:229} INFO - Heartbeat recovered after 11.41 seconds
[2025-03-09T23:33:01.926+0000] {spark_submit.py:641} INFO - 25/03/09 23:33:00 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:33:13.947+0000] {spark_submit.py:641} INFO - 25/03/09 23:33:13 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:33:25.543+0000] {spark_submit.py:641} INFO - 25/03/09 23:33:25 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@196fa59f)) by listener HeartbeatReceiver took 1.824900043s.
[2025-03-09T23:33:26.344+0000] {spark_submit.py:641} INFO - 25/03/09 23:33:25 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@196fa59f)) by listener AppStatusListener took 7.057393649s.
[2025-03-09T23:34:05.897+0000] {spark_submit.py:641} INFO - 25/03/09 23:33:27 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:35:07.818+0000] {spark_submit.py:641} INFO - 25/03/09 23:33:48 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:35:24.168+0000] {spark_submit.py:641} INFO - 25/03/09 23:34:00 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:35:53.039+0000] {spark_submit.py:641} INFO - 25/03/09 23:34:19 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:36:04.801+0000] {spark_submit.py:641} INFO - 25/03/09 23:34:33 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:36:13.900+0000] {spark_submit.py:641} INFO - 25/03/09 23:34:47 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:36:39.032+0000] {spark_submit.py:641} INFO - 25/03/09 23:35:00 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:33:02.614+0000] {job.py:239} ERROR - Job heartbeat failed with error
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/job.py", line 233, in heartbeat
    heartbeat_callback(session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/jobs/local_task_job_runner.py", line 284, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2359, in refresh_from_db
    _refresh_from_db(task_instance=self, session=session, lock_for_update=lock_for_update)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 872, in _refresh_from_db
    ti = TaskInstance.get_task_instance(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2345, in get_task_instance
    return query.one_or_none()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-03-09T23:37:00.748+0000] {spark_submit.py:641} INFO - 25/03/09 23:35:13 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:37:08.461+0000] {spark_submit.py:641} INFO - 25/03/09 23:35:28 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:37:04.636+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-09T23:37:20.921+0000] {spark_submit.py:641} INFO - 25/03/09 23:35:29 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@4861a79)) by listener HeartbeatReceiver took 1.820907074s.
[2025-03-09T23:37:23.828+0000] {spark_submit.py:641} INFO - 25/03/09 23:35:43 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:37:29.136+0000] {spark_submit.py:641} INFO - 25/03/09 23:35:47 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@4861a79)) by listener AppStatusListener took 12.116998815s.
[2025-03-09T23:37:30.178+0000] {spark_submit.py:641} INFO - 25/03/09 23:35:58 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:37:33.280+0000] {spark_submit.py:641} INFO - 25/03/09 23:36:13 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:37:37.147+0000] {spark_submit.py:641} INFO - 25/03/09 23:36:30 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:37:53.569+0000] {spark_submit.py:641} INFO - 25/03/09 23:36:38 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@3360fa59)) by listener AppStatusListener took 6.150955412s.
[2025-03-09T23:37:55.815+0000] {spark_submit.py:641} INFO - 25/03/09 23:36:47 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:37:58.361+0000] {spark_submit.py:641} INFO - 25/03/09 23:36:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:38:01.722+0000] {spark_submit.py:641} INFO - 25/03/09 23:37:06 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@3360fa59)) by listener SQLAppStatusListener took 1.784280156s.
[2025-03-09T23:38:05.696+0000] {spark_submit.py:641} INFO - 25/03/09 23:37:14 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:38:08.362+0000] {spark_submit.py:641} INFO - 25/03/09 23:37:21 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@1f8af8bf)) by listener AppStatusListener took 2.39040752s.
[2025-03-09T23:38:20.546+0000] {spark_submit.py:641} INFO - 25/03/09 23:37:27 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:38:27.610+0000] {spark_submit.py:641} INFO - 25/03/09 23:37:29 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@767fcf2f)) by listener AppStatusListener took 5.355318637s.
[2025-03-09T23:38:31.853+0000] {spark_submit.py:641} INFO - 25/03/09 23:37:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:38:37.207+0000] {spark_submit.py:641} INFO - 25/03/09 23:37:57 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:38:45.381+0000] {job.py:254} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-03-09T23:38:45.472+0000] {spark_submit.py:641} INFO - 25/03/09 23:38:00 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@53c11b9e)) by listener AppStatusListener took 1.944692972s.
[2025-03-09T23:38:54.054+0000] {spark_submit.py:641} INFO - 25/03/09 23:38:12 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:39:04.994+0000] {spark_submit.py:641} INFO - 25/03/09 23:38:23 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@6747818d)) by listener AppStatusListener took 3.627791436s.
[2025-03-09T23:38:55.197+0000] {local_task_job_runner.py:228} ERROR - Heartbeat time limit exceeded!
[2025-03-09T23:39:18.029+0000] {spark_submit.py:641} INFO - 25/03/09 23:38:27 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:39:19.269+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-09T23:39:22.414+0000] {spark_submit.py:641} INFO - 25/03/09 23:38:35 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@2fc0d2da)) by listener AppStatusListener took 4.068684204s.
[2025-03-09T23:39:28.286+0000] {spark_submit.py:641} INFO - 25/03/09 23:38:45 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:39:35.929+0000] {spark_submit.py:641} INFO - 25/03/09 23:39:04 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:39:46.157+0000] {process_utils.py:132} INFO - Sending 15 to group 1684. PIDs of all processes in the group: [1686, 1737, 1684]
[2025-03-09T23:39:55.825+0000] {spark_submit.py:641} INFO - 25/03/09 23:39:16 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2025-03-09T23:40:51.223+0000] {spark_submit.py:641} INFO - 25/03/09 23:39:06 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@274e66ba)) by listener AppStatusListener took 8.314817367s.
[2025-03-09T23:40:48.467+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1684
[2025-03-09T23:41:07.200+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-09T23:41:07.582+0000] {spark_submit.py:767} INFO - Sending kill signal to spark-submit
[2025-03-09T23:41:07.737+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1737, status='terminated', started='23:30:34') (1737) terminated with exit code None
[2025-03-09T23:41:09.015+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 555, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 641, in _process_spark_submit_log
    self.log.info(line)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/file_task_handler.py", line 274, in emit
    self.handler.emit(record)
  File "/usr/local/lib/python3.12/logging/handlers.py", line 75, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1280, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/__init__.py", line 705, in format
    record.asctime = self.formatTime(record, self.datefmt)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/timezone_aware.py", line 47, in formatTime
    s = self.default_msec_format % (s, record.msecs)
        ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-03-09T23:41:09.361+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_gcs_job, task_id=submit_spark_gcs_job, run_id=manual__2025-03-09T23:30:30.057279+00:00, execution_date=20250309T233030, start_date=20250309T233031, end_date=20250309T234109
[2025-03-09T23:41:09.510+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-09T23:41:09.547+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1684, status='terminated', exitcode=2, started='23:30:31') (1684) terminated with exit code 2
[2025-03-09T23:41:09.548+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1686, status='terminated', started='23:30:31') (1686) terminated with exit code None
